unicef/intervention-tab-pages

common/layout/etools-warn-message.ts
common/selectors.ts
intervention-details/gender-equity-rating/gender-equity-rating.ts
intervention-details/unicef-details/unicef-details.ts
intervention-management/amendments/pd-amendments.ts
intervention-management/fund-reservations/fund-reservations.ts
intervention-management/programmatic-visits/programmatic-visits.ts
intervention-overview/intervention-overview.ts
intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/results-structure/results-structure.ts
intervention-results/supply-agreement/supply-agreement.ts
intervention-tabs.ts
intervention-timing/reporting-requirements/partner-reporting-requirements.ts

[ch22067]Plugin into PMP fixes

---

common/mixins/component-base-mixin.ts
common/mixins/data-mixin.ts
utils/utils.ts

[ch22113]Fix endless re-render

---

common/models/intervention.types.ts
intervention-results/budget-summary/budget-summary.ts
intervention-results/budget-summary/budgetSummary.models.ts
intervention-results/budget-summary/budgetSummary.selectors.ts

[ch21338]PD results - Budget-summary component

[ch21338]PD results - Budget-summary component

---

intervention-management/intervention-management.ts
intervention-management/risks/risk-dialog.ts
intervention-management/risks/risk.models.ts
intervention-management/risks/risk.selectors.ts
intervention-management/risks/risks.ts

[ch21963] PD Management - Risks component

[ch21963] PD Management - Risks component

---

common/mixins/component-base-mixin.ts

[ch22128] Display '-' when email or phone are empty

[ch22128] Display '-' when email or phone are empty

---

intervention-details/gender-equity-rating/gender-equity-rating.ts

[ch22099] Gender-equity-rating handle loading spinner

[ch22099] Gender-equity-rating handle loading spinner

---

intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch21615] PD results - Supply Agreement component

[ch21615] PD results - Supply Agreement component refactorings

---

common/models/intervention.types.ts
intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch22161]Fix error on save supply agreement

---

intervention-management/final-review/final-review-popup.ts
intervention-results/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/modals/cp-output-dialog.ts
intervention-results/results-structure/modals/pd-output-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch22163] Supply-agreement - error on displaying selected cp outputs

[ch22163] Supply-agreement - error on displaying selected cp outputs

---

common/components/comments/comments-dialog.ts
common/mixins/endpoints-mixin.ts
common/models/globals.types.ts
intervention-details/details-overview/details-overview.ts
intervention-details/document-details/document-details.ts
intervention-details/gender-equity-rating/gender-equity-rating.ts
intervention-details/geographical-coverage/geographical-coverage.ts
intervention-details/geographical-coverage/grouped-locations-dialog.ts
intervention-details/partner-details/partner-details.ts
intervention-details/technical-guidance-capacity/technical-guidance.ts
intervention-details/unicef-details/unicef-details.ts
intervention-management/amendments/add-amendment-dialog.ts
intervention-management/amendments/pd-amendments.ts
intervention-management/financial/financial-component.ts
intervention-management/programmatic-visits/programmatic-visits.ts
intervention-management/review-and-sign/review-and-sign.ts
intervention-management/risks/risks.ts
intervention-overview/intervention-overview.ts
intervention-progress/intervention-progress.ts
intervention-results/budget-summary/budget-summary.ts
intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.ts
intervention-results/supply-agreement/supply-agreement.ts
intervention-tabs.ts
intervention-timing/activity-timeframes/activity-timeframes.ts
intervention-timing/intervention-dates/intervention-dates.ts
intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
intervention-timing/reporting-requirements/partner-reporting-requirements.ts
intervention-timing/timing-overview/timing-overview.ts

[ch22126] Define redux state type/interface for intervention-tab-pages

[ch22126] Define redux state type/interface for intervention-tab-pages

---

intervention-management/review-and-sign/review-and-sign.ts

[ch22176]Submited to PRC editable while in readonly mode

[ch22176]Submited to PRC editable while in readonly mode

---

intervention-management/review-and-sign/review-and-sign.ts

[ch21975]PD Management - Signed Documents and Signatories component

[ch21975]PD Management - Signed Documents and Signatories component tweaks

---

intervention-results/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts

[ch22165] Format of the data sent on edit Effective&Efficient Prgm Mgmt is not correct

[ch22165] Format of the data sent on edit Effective&Efficient Prgm Mgmt is not correct

---

intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.ts

[ch22155]Results-structure - use permissions matrix

---

intervention-results/results-structure/modals/indicator-dialog/cluster-indicator.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dialog.ts

[ch22187]Indicator -Display prp disaggregations

---

intervention-details/document-details/document-details.ts

[ch22184] Document-details component - make Title textarea(multi line)

[ch22184] Document-details component - make Title textarea(multi line)

---

common/mixins/fr-numbers-consistency-mixin.ts
intervention-results/budget-summary/budget-summary.ts

[ch22093]Budget Summary component - show fund reservation related warnings

[ch22093]Budget Summary component - show fund reservation related warnings

---

intervention-details/details-overview/details-overview.ts
intervention-details/details-overview/interventionOverview.models.ts
intervention-timing/intervention-dates/intervention-dates.ts
intervention-timing/intervention-dates/interventionDates.models.ts

[ch22125]Activation Letter for Contingency PD

---

common/mixins/component-base-mixin.ts
intervention-details/partner-details/partner-details.ts
intervention-details/partner-details/partnerDetails.models.ts
intervention-details/unicef-details/unicef-details.ts

[ch22207]Optimize email, phone display

---

intervention-timing/activity-timeframes/activity-timeframes.ts

[ch22205] Show message when there are no Activity Timeframes

[ch22205] Show message when there are no Activity Timeframes

---

intervention-details/details-overview/details-overview.ts
intervention-details/document-details/document-details.ts
intervention-details/geographical-coverage/geographical-coverage.ts
intervention-details/geographical-coverage/grouped-locations-dialog.ts
intervention-details/technical-guidance-capacity/technical-guidance.ts
intervention-management/amendments/add-amendment-dialog.ts
intervention-management/final-review/final-review.ts
intervention-management/financial/financial-component.ts
intervention-management/programmatic-visits/programmatic-visits.ts
intervention-management/review-and-sign/review-and-sign.ts
intervention-reports/intervention-reports.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.ts
intervention-results/supply-agreement/supply-agreement.ts
intervention-timing/intervention-dates/intervention-dates.ts
intervention-timing/reporting-requirements/partner-reporting-requirements.ts
intervention-timing/timing-overview/timing-overview.ts

[ch22208] Avoid executing 'stateChanged' when not needed

[ch22208] Avoid executing 'stateChanged' when not needed

---

intervention-management/risks/risk.models.ts
intervention-management/risks/risks.ts

[ch22220] Risks component - style issues

[ch22220] Risks component - style issues

---

common/styles/shared-styles-lit.ts
intervention-tabs.ts

[ch22223] intervention-tab-pages content panel header should be white like in ePD

[ch22223] intervention-tab-pages content panel header should be white like in ePD

---

intervention-overview/intervention-overview.ts

[ch22237] Refresh on Overview page   - flash of console error

[ch22237] Refresh on Overview page   - flash of console error

---

intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/modals/activity-dialog/activity-items-table.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.ts

[ch22255] Inconsistency in 'Add' icon

[ch22255] Inconsistency in 'Add' icon

---

intervention-overview/intervention-overview.ts

[ch22235] Unicef Cash Contribution and Total Unicef Contribution not aligned with sums

[ch22235] Unicef Cash Contribution and Total Unicef Contribution not aligned with sums

---

intervention-details/intervention-details.ts
intervention-details/partner-details/partner-info.ts
intervention-details/partner-details/partnerInfo.models.ts
intervention-details/partner-details/partnerInfo.selectors.ts

[ch22268]Rename partner-details to avoid clash in PMP

---

common/models/globals.types.ts
common/models/intervention.types.ts
intervention-management/risks/risk-dialog.ts
intervention-management/risks/risk.models.ts
intervention-management/risks/risk.selectors.ts
intervention-management/risks/risks.ts
utils/intervention-endpoints.ts

[ch22186] Risks component tweaks/bk needs

[ch22186] Risks component tweaks/bk needs

---

intervention-results/results-structure/pd-indicator.ts

[ch22253] Styling issue at indicator buttons

[ch22253] Styling issue at indicator buttons

---

common/styles/shared-styles-lit.ts

[ch22242] Inactive scroll after Save

[ch22242] Inactive scroll after Save

---

common/styles/shared-styles-lit.ts
intervention-attachments/intervention-attachment-dialog.ts
intervention-tabs.ts

[ch22299] Gray overwriting by black in content-panel

[ch22299] Gray overwriting by black in content-panel

---

intervention-results/results-structure/modals/activity-dialog/activity-item-row.ts

[ch22249]Fix input level total calculation

---

intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch22307]Fix del activity input level

---

intervention-management/amendments/pd-amendments.ts
intervention-management/review-and-sign/review-and-sign.ts
intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/results-structure/results-structure.ts
intervention-results/supply-agreement/supply-agreement.ts
intervention-timing/activity-timeframes/activity-timeframes.ts
utils/request-helper.ts

[ch22247]Fix ui update on cancel after bk err

---

common/models/intervention.types.ts
intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts
intervention-results/supply-agreement/supplyAgreement.selectors.ts

[ch22149] Supply-agreement component tweaks/bk needs

[ch22149] Supply-agreement component tweaks/bk needs

---

intervention-overview/intervention-overview.ts

[ch22285] Overview: Remove hand pointer for Partner name

[ch22285] Overview: Remove hand pointer for Partner name

---

intervention-results/results-structure/modals/indicator-dialog/indicator-dialog.ts

[ch22302] Prevent partner user from defining disaggregations

[ch22302] Prevent partner user from defining disaggregations

---

intervention-management/amendments/pd-amendments.ts
intervention-management/fund-reservations/fund-reservations.ts
intervention-management/risks/risks.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch22355] Change add icon from + to the other icon

[ch22355] Change add icon from + to the other icon

---

intervention-management/amendments/pd-amendments.ts

[ch22358] Hide the add btn for Amendments

[ch22358] Hide the add btn for Amendments

---

common/layout/icons-actions.ts
intervention-timing/reporting-requirements/hr/hru-list.ts
intervention-timing/reporting-requirements/qpr/qpr-list.ts
intervention-timing/reporting-requirements/srr/special-reporting-requirements.ts

[ch22370]Rename icons-actions

---

common/mixins/component-base-mixin.ts
intervention-details/unicef-details/unicef-details.ts

[ch22359]Fix selected users details display

---

intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/results-structure.ts

[ch22353] Results structure - by default show the section expanded not collapsed

[ch22353] Results structure - by default show the section expanded not collapsed

---

intervention-attachments/intervention-attachment-dialog.ts

[ch22379]Cannot save attachments

[ch22379]Cannot save attachments

---

intervention-management/final-review/final-review-popup.ts

[ch22401]Cannot save Final Partnership Review Attachment

[ch22401]Cannot save Final Partnership Review Attachment

---

common/layout/page-content-header/intervention-page-content-header.ts
intervention-timing/activity-timeframes/activity-timeframes.styles.ts

[ch22116] Dividers are invisible in PMP (style issue)

[ch22116] Dividers are invisible in PMP (style issue)

---

common/config.ts
common/constants.ts
common/mixins/pagination-mixin.ts
common/styles/required-field-styles.ts
config/config.ts

[ch22405] Remove constants from config/config file

[ch22405] Remove constants from config/config file

---

intervention-results/results-structure/pd-indicator.ts

[ch22413]Percentage Indicator display type baseline

[ch22413]Percentage Indicator display type baseline

---

intervention-results/results-structure/pd-indicator.ts

[ch22361] Indicator types styles not working anymore

[ch22361] Indicator types styles not working anymore

---

intervention-details/unicef-details/unicef-details.ts

[ch22453]Unicef-details - loading spinner not shown after click on Save

[ch22453]Unicef-details - loading spinner not shown after click on Save

---

intervention-details/geographical-coverage/grouped-locations-dialog.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dialog.ts
intervention-results/results-structure/modals/indicator-dialog/mixins/save-indicator-mixin.ts
intervention-results/results-structure/modals/indicator-dialog/types.ts
intervention-results/results-structure/pd-indicators.ts
intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
intervention-timing/reporting-requirements/hr/humanitarian-reporting-req-unicef.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
intervention-timing/reporting-requirements/qpr/quarterly-reporting-requirements.ts
intervention-timing/reporting-requirements/srr/add-edit-special-rep-req.ts
intervention-timing/reporting-requirements/srr/special-reporting-requirements.ts

[ch22421]'toastEventSource' no longer needed

[ch22421]'toastEventSource' no longer needed

---

intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/results-structure.ts

[ch22159] Results-structure hover style issue

[ch22159] Results-structure hover style issue

---

common/layout/export-intervention-data.ts
common/mixins/component-base-mixin.ts
intervention-actions/intervention-actions.ts
intervention-attachments/attachments-list.ts
intervention-attachments/intervention-attachment-dialog.ts
intervention-details/gender-equity-rating/gender-equity-rating.ts
intervention-details/geographical-coverage/geographical-coverage.ts
intervention-details/unicef-details/unicef-details.ts
intervention-management/amendments/pd-amendments.ts
intervention-management/final-review/final-review.ts
intervention-management/fund-reservations/fund-reservations.ts
intervention-management/fund-reservations/update-fr-numbers.ts
intervention-management/programmatic-visits/programmatic-visits.ts
intervention-management/risks/risks.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/modals/activity-dialog/activity-item-row.ts
intervention-results/results-structure/modals/cp-output-dialog.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts
intervention-results/results-structure/modals/pd-output-dialog.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicator.ts
intervention-results/results-structure/results-structure.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch22482] Use @click instead of @tap

[ch22482] Use @click instead of @tap

---

intervention-details/details-overview/details-overview.ts

[ch22492] Rename CFEI label in PD

[ch22492] Rename CFEI label in PD

---

common/models/intervention.types.ts
intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/modals/cp-output-dialog.ts
intervention-results/results-structure/modals/pd-output-dialog.ts
intervention-results/results-structure/pd-indicator.ts
intervention-results/results-structure/results-structure.ts
utils/intervention-endpoints.ts

[ch22474]Possibility to delete CP and PD Output from PD

---

intervention-results/results-structure/pd-indicator.ts
intervention-results/results-structure/pd-indicators.ts

[ch22433]Results Structure: Display of multiple locations in indicator details

[ch22433]Results Structure: Display of multiple locations in indicator details

---

intervention-details/gender-equity-rating/gender-equity-rating.ts
intervention-details/gender-equity-rating/genderEquityRating.models.ts

[ch22454]Gender-equity-rating - text fields should not be required

[ch22454]Gender-equity-rating - text fields should not be required

---

common/layout/are-you-sure.ts

[ch22381] Rearrange text from Confirmation Box

[ch22381] Rearrange text from Confirmation Box

---

intervention-details/details-overview/details-overview.ts
intervention-management/risks/risk-dialog.ts
intervention-management/risks/risks.ts

[ch22244] Dialogs refactoring

---

intervention-details/unicef-details/pdUnicefDetails.models.ts
intervention-details/unicef-details/unicef-details.ts

[ch22547]Unicef-details - `unicef_office` should be replaced with `offices`

[ch22547]Unicef-details - `unicef_office` should be replaced with `offices`

---

intervention-details/geographical-coverage/geographical-coverage.ts

[ch22550] Geographical-coverrage - don't show SEE ALL when there are no locations selected

[ch22550] Geographical-coverrage - don't show SEE ALL when there are no locations selected

---

intervention-overview/intervention-overview.ts

[ch22340] PD Overview tab: Include Partner PSEA Risk rating with a link to a filtered list for engagements for each

[ch22340] PD Overview tab: Include Partner PSEA Risk rating with a link to a filtered list for engagements for each

---

common/actions.ts

[ch22611], [ch22584], [ch22587] Temporary fix for planned_budget coming null from BE

[ch22611], [ch22584], [ch22587] Temporary fix for planned_budget coming null from BE

---

common/mixins/repeatable-data-sets-mixin.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts

[ch22552]Add/edit Indicator dialog - Disaggregation tab counter not updated on delete disaggregation

[ch22552]Add/edit Indicator dialog - Disaggregation tab counter not updated on delete disaggregation

---

intervention-actions/intervention-actions.ts

[ch22437] Action buttons not working / Method POST not allowed

[ch22437] Action buttons not working / Switch from POST to PATCH

---

intervention-details/gender-equity-rating/gender-equity-rating.ts
intervention-details/unicef-details/unicef-details.ts

[ch22247]Fix consecutive edits, then cancel on gender-equity-rating

---

common/constants.ts
common/mixins/component-base-mixin.ts
intervention-details/details-overview/details-overview.ts
intervention-details/unicef-details/unicef-details.ts

[ch22549]Pd Document Type - display the long version on the UI

[ch22549]Pd Document Type - display the long version on the UI

---

common/models/globals.types.ts
intervention-management/financial/financial-component.ts

[ch22167]PD Management - Financial component tweaks/bk needs

[ch22167]PD Management - Financial component tweaks/bk needs

---

intervention-management/final-review/final-review-popup.ts

[ch22546]final-review-popup - refactor/clean up

[ch22546]final-review-popup - refactor/clean up

---

intervention-actions/intervention-actions.ts

[ch22625]Update UI after action btn click

---

intervention-results/results-structure/pd-indicator.ts
intervention-results/results-structure/results-structure.styles.ts

[ch22594] Improve display on indicators details

[ch22594] Improve display on indicators details

---

common/models/intervention.types.ts
intervention-overview/intervention-overview.ts

[ch22267] PD overview tab - display cash values/bk needs

[ch22267] PD overview tab - display cash values/bk needs

---

intervention-management/fund-reservations/fund-reservations.ts

[ch22674]Management Tab: Fund Reservations not collapsable

[ch22674]Management Tab: Fund Reservations not collapsable

---

intervention-details/geographical-coverage/geographical-coverage.ts

[ch22628] Geographical coverage - SEE ALL link height

[ch22628] Geographical coverage - SEE ALL link height

---

intervention-details/partner-details/partner-info.ts
intervention-details/unicef-details/pdUnicefDetails.models.ts
intervention-details/unicef-details/unicef-details.ts

[ch22660]Update permission field name, fix consecutive edits,tweak user display

---

utils/utils.ts

[ch22668]Fix null related error

---

intervention-results/budget-summary/budget-summary.ts

Show % on results overview page

---

common/styles/shared-styles-lit.ts
intervention-attachments/attachments-list.styles.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicator.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.styles.ts
intervention-results/results-structure/results-structure.ts

[ch22481]'.editable-row .hover-block' & related styles should be reused

[ch22481]'.editable-row .hover-block' & related styles should be reused

---

intervention-actions/intervention-actions.ts

[ch22645] Show confirmation dialogs on action buttons click

[ch22645] Show confirmation dialogs on action buttons click

---

intervention-timing/reporting-requirements/hr/hru-list.ts

[ch22398] Shadow box over edit/delete sign and alignment issues in Partner Reporting components

[ch22398] Shadow box over edit/delete sign and alignment issues in Partner Reporting components

---

common/styles/shared-styles-lit.ts
intervention-overview/intervention-overview.ts

[ch22638] Refresh page on Overview tab changes styles

[ch22638] Refresh page on Overview tab changes styles

---

intervention-results/budget-summary/budget-summary.ts
intervention-results/budget-summary/budgetSummary.models.ts

[ch22150]Map bk values to budget summary

---

intervention-tabs.ts

[ch22376]Fix intermittent store undefined error

---

intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/effective-efficient-programme-mgmt/effectiveEfficientProgrammeMgmt.models.ts

[ch22698] Show currency also, for Effective&Efficient Prgmt Mgmt TOTAL

[ch22698] Show currency also, for Effective&Efficient Prgmt Mgmt TOTAL

---

intervention-management/financial/financial-component.ts
intervention-management/financial/financialComponent.selectors.ts

[ch22705] Saved document currency not preserved after browser refresh

[ch22705] Saved document currency not preserved after browser refresh

---

intervention-details/unicef-details/unicef-details.ts

[ch22795] Intervention clusters not displayed in Details tab/Unicef Details  section

[ch22795] Intervention clusters not displayed in Details tab/Unicef Details  section

---

intervention-actions/intervention-actions.ts

[ch22779]Send to Partner confirmation box

[ch22779]Send to Partner confirmation box typo

---

intervention-results/results-structure/pd-indicators.ts

[ch22793] Improve awareness on deactivating an indicator

[ch22793] Improve awareness that you can't undo indicator deactivation

---

intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch22673]Results Structure: Add activity required fields

[ch22673]Results Structure/ Activity: Add FE validation for required fields

---

intervention-management/financial/financial-component.ts

[ch22646]Financial component - values not reset on cancel

[ch22646]Financial component - values not reset on cancel

---

intervention-results/budget-summary/budget-summary.ts

[ch22678]Results tab-budget section: incorrect display of financial values

[ch22678]Results tab-budget section: incorrect display of financial values

---

intervention-tabs.ts
utils/utils.ts

[ch22337] Reflect Comment mode in url

[ch22337] Reflect Comment mode in url

---

intervention-overview/intervention-overview.ts

[ch22697]PD Overview tab - show '%' char for Total value

[ch22697]PD Overview tab - show '%' char for Total value

---

intervention-results/results-structure/pd-activities.ts

[ch22826]Results Structure/ Add Activity - %NaN displayed when cash values are 0

[ch22826]Results Structure/ Add Activity - %NaN displayed when cash values are 0

---

intervention-results/results-structure/pd-activities.ts

[ch22802]Results Structure/Activities - Add ability to delete an activity

[ch22802]Results Structure/Activities - Add ability to delete an activity

---

intervention-results/results-structure/modals/indicator-dialog/cluster-indicator.ts
intervention-results/results-structure/pd-indicator.ts
intervention-results/results-structure/pd-indicators.ts

[ch22791] Cluster Indicators are not displayed in the list.

[ch22791] Cluster Indicators are not displayed in the list

---

intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/results-structure.ts

[ch22416]Results Structure/Add btn style fix

---

common/actions.ts
common/components/prp-country-data/prp-country-data.ts
common/mixins/endpoints-mixin-lit.ts
common/mixins/endpoints-mixin.ts
intervention-results/results-structure/modals/indicator-dialog/cluster-indicator.ts
intervention-tabs.ts
intervention-timing/reporting-requirements/hr/humanitarian-reporting-req-cluster.ts
utils/intervention-endpoints.ts

[ch22036] Handle requests to PRP from intervention-tab-pages

[ch22036] Handle requests to PRP from intervention-tab-pages

---

intervention-actions/intervention-actions.constants.ts
intervention-actions/intervention-actions.ts

[ch22844]accept_review typo

---

intervention-tabs.ts

[ch22849]Fix status not updating after action click

---

intervention-actions/reason-popup.ts

[ch22840]Cancelation reason input not available when on Overview tab

---

common/layout/status/intervention-report-status.ts
intervention-progress/intervention-progress.ts
intervention-reports/intervention-reports.ts

[ch22902] Rename report-status

[ch22902] Rename report-status

---

intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch22751] Money values are not formatted everywhere

[ch22751] Money values are not formatted everywhere

---

intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/results-structure.ts

[ch22669] Results Structure: check permission matrix adding indicator, activity and PD Output

[ch22669] Results Structure: check permission matrix adding indicator, activity and PD Output

---

intervention-management/financial/financial-component.ts

[ch22287]Fix save currency 

---

intervention-timing/timing-overview/timing-overview.ts
intervention-timing/timing-overview/timingOverview.models.ts

[ch22221]PD timing - Overview component / map FE to bk fields

[ch22221]PD timing - Overview component / map FE to bk fields

---

intervention-management/review-and-sign/managementDocument.model.ts

[ch22890]Management tab/Signatures&Dates - edit icon available when all fields are readonly

[ch22890]Management tab/Signatures&Dates - edit icon available when all fields are readonly

---

intervention-results/results-structure/modals/indicator-dialog/mixins/save-indicator-mixin.ts
utils/intervention-endpoints.ts

[ch22829]Update add indicator endpoint

---

intervention-details/document-details/document-details.ts
intervention-management/risks/risk-dialog.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch22895] Message 'This field is required' is missing

[ch22895] Message 'This field is required' is missing

---

intervention-management/review-and-sign/review-and-sign.ts

[ch22897] Eager validation on Dates&Signatures when navigating between PDs

[ch22897] Eager validation on Dates&Signatures when navigating between PDs

---

common/components/intervention/pd-termination.ts

[ch22143] Update code that uses SSFA checks

[ch22143] Update SSFA labels

---

intervention-details/geographical-coverage/geographical-coverage.ts

[ch22800] Locations drop-down moves to the left

[ch22800] Locations drop-down moves to the left

---

common/mixins/repeatable-data-sets-mixin.ts
intervention-management/fund-reservations/fund-reservations.ts
intervention-management/fund-reservations/update-fr-numbers.ts
intervention-management/programmatic-visits/programmatic-visits.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dialog.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts
intervention-results/results-structure/modals/indicator-dialog/mixins/save-indicator-mixin.ts

[ch22920] Remove repeatable-data-sets-mixin

[ch22920] Refactor repeatable-data-sets-mixin

---

intervention-details/unicef-details/unicef-details.ts

[ch22993] Hide Budget Owner field for partner user

[ch22993] Hide Budget Owner field for partner user

---

intervention-details/document-details/document-details.ts
intervention-details/intervention-details.ts
intervention-management/amendments/add-amendment-dialog.ts
intervention-management/risks/risk-dialog.ts
intervention-results/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-timing/intervention-dates/intervention-dates.ts
intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts

[ch22997] Move geographical coverage up on UI & label tweaks

[ch22997] Move geographical coverage up on UI & label tweaks

---

intervention-details/unicef-details/unicef-details.ts

[ch23000] Selected Sections, Offices not visible to partner user

[ch23000] Selected Sections, Offices not visible to partner user

---

intervention-progress/intervention-progress.ts

[ch22143] Update code that uses SSFA checks

[ch22143]Remove SSFA labels

---

common/layout/are-you-sure.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/modals/activity-dialog/activity-item-row.ts
intervention-results/results-structure/modals/activity-dialog/activity-items-table.ts
intervention-results/results-structure/modals/activity-dialog/activity-timeframes.ts
intervention-results/results-structure/modals/indicator-dialog/cluster-indicator.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dialog.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts
intervention-results/results-structure/modals/indicator-dialog/non-cluster-indicator.ts
intervention-results/results-structure/modals/indicator-dialog/types.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicator.ts
intervention-results/results-structure/pd-indicators.ts

[ch22996] Ability to view indicators and activity details when they're not editable

[ch22996] Ability to view indicators and activity details when they're not editable

---

intervention-overview/intervention-overview.ts

[ch22998]Overview tab - align number values to the left

[ch22998]Overview tab - align number values to the left

---

intervention-results/supply-agreement/supply-agreement-dialog.ts

[ch23057] Available CP Outputs for Supply agreement when there are unassociated PD Outputs

[ch23057] Available CP Outputs for Supply agreement when there are unassociated PD Outputs

---

intervention-results/results-structure/results-structure.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch23037]After deleting Budget items, re-GET intervention

[ch23037]After deleting Budget items, re-GET intervention

---

intervention-reports/intervention-reports.ts

[ch23050] Wrong data shown in Reports tab

[ch23050] Wrong data shown in Reports tab

---

intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts

[ch23073]Add requirements for Humanitarian reports - no toast present for not selecting current day

[ch23073]Add requirements for Humanitarian reports - no toast present for not selecting current day

---

intervention-attachments/intervention-attachment-dialog.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch23075]Edit dialog : change OK to Save button

[ch23075]Edit dialog : change OK to Save button

---

intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch23094] Add Pd output activity - persistent validation err message

[ch23094] Add Pd output activity - persistent validation err message

---

intervention-results/results-structure/cp-output-level.ts

[ch23085] Show entire text for Ram Indicators

[ch23085] Show entire text for Ram Indicators

---

common/components/cancel/cancel-justification.ts
common/models/intervention.types.ts
intervention-actions/intervention-actions.ts
intervention-tabs.ts

[ch22975]Show cancelation reason on the UI

[ch22975]Show cancelation reason on the UI

---

common/models/intervention.types.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/results-structure.ts

[ch23019]Results Structure/ Show Total Cash Budget for CP Output & PD Output

[ch23019]Results Structure/ Show Total Cash Budget for CP Output & PD Output

---

intervention-management/final-review/final-review.ts
intervention-management/financial/financial-component.ts
intervention-management/review-and-sign/review-and-sign.ts
intervention-management/risks/risks.ts
intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/results-structure.ts
intervention-timing/timing-overview/timing-overview.ts

[ch22997] label capitalization fix

[ch22997] label capitalization fix

---

intervention-details/partner-details/partner-info.ts

[ch22523]Fix selected agreement not shown - intermittent

---

intervention-management/financial/financial-component.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/pd-activities.ts

[ch23114]Fix spaces, placeholders, labels

---

common/components/intervention/pd-termination.ts
intervention-actions/intervention-actions.constants.ts
intervention-actions/intervention-actions.ts
intervention-management/review-and-sign/managementDocument.model.ts
intervention-management/review-and-sign/review-and-sign.ts

[ch22164]Terminate PD functionality

[ch22164]Terminate PD functionality

---

intervention-management/financial/financial-component.ts

[ch22705]Fix currency not shown after page refresh

---

intervention-results/results-structure/modals/indicator-dialog/non-cluster-indicator.ts

[ch23156] Add indicator dialog: blue halo on Add all button

[ch23156] Add indicator dialog: blue halo on Add all button

---

intervention-overview/fund-reservations-display/fund-reservations-display.ts

[ch11173] In the PD/SSFA Overview - Implementation Status - FC Line Item should include more detail

[ch11173] In the PD/SSFA Overview - Implementation Status - FC Line Item should include more detail

---

common/layout/export-intervention-data.ts
intervention-actions/intervention-actions.ts
utils/intervention-endpoints.ts

[ch23182]Export comments

---

common/styles/shared-styles-lit.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts

[ch23150] Intermittent dropdown issues

[ch23150] Intermittent dropdown issues

---

intervention-overview/fund-reservations-display/fund-reservations-display.ts

[ch23165] Overview tab - Static row behaving as clickable/actionable

[ch23165] Overview tab - Static row behaving as clickable/actionable

---

intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch23183]Supply Agreement - Hide CP Outputs for Partner user

[ch23183]Supply Agreement - Hide CP Outputs for Partner user

---

intervention-timing/reporting-requirements/partner-reporting-requirements.ts

[ch21619]PD timing - Reporting Requirements component

[ch21619]PD timing - Reporting Requirements component- hide cluster reports for partner

---

intervention-results/supply-agreement/supply-agreement.ts

[ch23112] Show `There are no [Items] added.` msg

[ch23112] Show `There are no [Items] added.` msg

---

intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/modals/activity-dialog/activity-timeframes.ts

[ch23253]On create Pd Output Activity show info msg if there are no Activity Timeframes available

[ch23253]On create Pd Output Activity show info msg if there are no Activity Timeframes available

---

intervention-results/results-structure/modals/indicator-dialog/cluster-indicator.ts
intervention-results/results-structure/modals/indicator-dialog/non-cluster-indicator.ts

[ch23134]Add/Edit PD output Indicators dialog- reduce distance/padding between rows

[ch23134]Add/Edit PD output Indicators dialog- reduce distance/padding between rows

---

common/actions.ts
intervention-tabs.ts

[ch23172]Prevent blink

---

intervention-results/results-structure/modals/indicator-dialog/non-cluster-indicator.ts

[ch23156] Add all button alignment

[ch23156] Add all button alignment

---

common/mixins/component-base-mixin.ts
common/styles/shared-styles-lit.ts
intervention-actions/reason-popup.ts
intervention-details/partner-details/partner-info.ts

[ch23280] Small style issues in 2 places

[ch23280] Small style issues in cancelation reason and user details

---

intervention-results/results-structure/modals/indicator-dialog/cluster-indicator.ts
intervention-results/results-structure/modals/indicator-dialog/non-cluster-indicator.ts

[ch23158]Add indicator (percentage type): Entering baseline value triggers Locations error message

[ch23158]Add indicator (percentage type): Entering baseline value triggers Locations error message

---

intervention-results/supply-agreement/supply-agreement.ts
utils/intervention-endpoints.ts

connected with
https://github.com/unicef/etools-partnership-management/pull/1509
https://github.com/unicef/etools-epd/pull/143

[ch23128] Add supply items csv import

---

common/mixins/repeatable-data-sets-mixin.ts
intervention-management/risks/risks.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicator.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch23287]Add ability to delete Pd Output Indicator while in Development/Draft status

[ch23287]Add ability to delete Pd Output Indicator while in Development/Draft status

---

intervention-management/final-review/final-review.ts

[ch23376]Use attachment_document instead of attachment_file

---

intervention-attachments/attachments-list.ts

[ch23378]Console error when going from any PD tab to PDs/SPDs list, or accessing Progress/Reports tab

[ch23378]Console error when going from any PD tab to PDs/SPDs list, or accessing Progress/Reports tab

---

intervention-results/results-structure/pd-indicator.ts

[ch23422]Fix display of disaggregations with no groups

---

common/actions.ts
intervention-results/results-structure/pd-indicator.ts
intervention-tabs.ts

[ch23414]Redirect to page-not-found when PD doesn't exist

---

common/components/comments/comment.ts

[ch23532] Comments not displayed as Resolved in Comments dialog

[ch23532] Comments not displayed as Resolved in Comments dialog

---

intervention-management/financial/financial-component.ts
intervention-management/review-and-sign/review-and-sign.ts
intervention-management/risks/risks.ts
intervention-results/budget-summary/budget-summary.ts
intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/results-structure/results-structure.ts
intervention-timing/intervention-dates/intervention-dates.ts

[ch23383]Fix console errors throughout the app

---

intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch23483] Edit Activity dialog shows Saving data instead of Loading at open

[ch23483] Edit Activity dialog shows Saving data instead of Loading at open

---

intervention-results/results-structure/results-structure.ts

[ch23035] Highlight editable rows on hover

[ch23035] Highlight editable rows on hover-fix for partner user

---

intervention-overview/intervention-overview.ts

[ch23577] PD Overview tab/ Hide CP Outputs for partner user & avoid unnecessary processings

[ch23577] PD Overview tab/ Hide CP Outputs for partner user & avoid unnecessary processings

---

common/styles/shared-styles-lit.ts
intervention-overview/fund-reservations-display/fund-reservations-display.ts

[ch23544] PD Implementation Status/ Improve external-icon display

[ch23544] PD Implementation Status/ Improve external-icon display

---

intervention-timing/reporting-requirements/partner-reporting-requirements.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts

[ch23507] Edit QPR Reporting Requirements

[ch23507] Edit QPR Reporting Requirements

---

common/components/cancel/cancel-justification.ts

[ch23557] Move Cancelation note label in the header of the component

[ch23557] Move Cancelation note label in the header of the component

---

intervention-management/risks/risk-dialog.ts
intervention-tabs.ts

[ch23629]Tweak chip style & add auto-validate for Risks

---

intervention-overview/intervention-overview.ts

[ch23363]Fix padding for implementation status& monitoring activities

---

intervention-results/supply-agreement/supply-agreement-dialog.ts

[ch23647] Supply Agreement/ validation msg missing and invalid state not going away after entering a value

fixed validations on supply agreeement dialog

---

intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts

[ch23630]Add.Edit QPR/ Validation message is shown only after the dialog has closed

[ch23630]Add.Edit QPR/ Validation message is shown only after the dialog has closed

---

intervention-details/details-overview/details-overview.ts
intervention-details/document-details/document-details.ts
intervention-details/gender-equity-rating/gender-equity-rating.ts
intervention-details/geographical-coverage/geographical-coverage.ts
intervention-details/partner-details/partner-info.ts
intervention-details/technical-guidance-capacity/technical-guidance.ts
intervention-details/unicef-details/unicef-details.ts
intervention-overview/fund-reservations-display/fund-reservations-display.ts
intervention-overview/intervention-overview.ts
intervention-overview/monitoring-visits-list/monitoring-visits-list-2.ts
intervention-results/budget-summary/budget-summary.ts
intervention-results/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/results-structure/modals/indicator-dialog/cluster-indicator-disaggregations.ts
intervention-results/results-structure/modals/indicator-dialog/cluster-indicator.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dialog.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts
intervention-results/results-structure/modals/indicator-dialog/non-cluster-indicator.ts
intervention-results/results-structure/results-structure.ts
intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch23538] Add the English language translations to the en.json file.

[ch23538] Add the English language translations to the en.json file.

---

intervention-results/results-structure/modals/cp-output-dialog.ts

[ch23483] Edit dialog shows Saving data instead of Loading at open

[ch23483] Edit dialog shows Saving data instead of Loading at open

---

common/layout/etools-form-element-wrapper.ts
common/layout/icons-actions.ts
intervention-overview/intervention-overview.ts
intervention-overview/monitoring-visits-list/monitoring-visits-list.ts
intervention-progress/intervention-progress.ts
intervention-timing/reporting-requirements/hr/hru-list.ts
intervention-timing/reporting-requirements/qpr/qpr-list.ts
intervention-timing/reporting-requirements/srr/special-reporting-requirements.ts

[ch22434] Handle duplicate components, with `-2` in their name

[ch22434] Handle duplicate components, with `-2` in their name

---

intervention-details/partner-details/partner-info.ts
intervention-details/partner-details/partnerInfo.models.ts
intervention-management/amendments/add-amendment-dialog.ts
intervention-management/review-and-sign/managementDocument.model.ts
intervention-management/review-and-sign/review-and-sign.ts
intervention-results/supply-agreement/supply-agreement-dialog.ts

[ch23813]Handle users that no longer exist or were moved to different countries - partner_focal_points , partner_authorized_officer_signatory 

---

intervention-details/partner-details/partner-info.ts
intervention-management/review-and-sign/review-and-sign.ts

[ch23810]Display selected users' email and phone in the Management tab also

---

intervention-tabs.ts
intervention-timing/timing-overview/timing-overview.ts
intervention-timing/timing-overview/timingOverview.models.ts

[ch23513]Replace date_draft_by_partner with submission_date

---

common/layout/export-intervention-data.ts
utils/intervention-endpoints.ts

[ch23783]Export PD pdf

---

intervention-management/final-review/final-review.ts
intervention-management/fund-reservations/fund-reservations.ts
intervention-timing/activity-timeframes/activity-timeframes.ts
intervention-timing/reporting-requirements/partner-reporting-requirements.ts

[ch22986] Switch from transparent colors in app-theme to plain colors

[ch22986] Switch from transparent colors in app-theme to plain colors

---

intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch23811] Supply Agreement/ Add optional field 'Unicef Product’ Number'

[ch23811] Supply Agreement/ Add optional field 'Unicef Product’ Number'

---

common/components/comments/comments-dialog.ts
common/mixins/utils-mixin.ts
intervention-actions/reason-popup.ts
intervention-attachments/intervention-attachment-dialog.ts
intervention-management/final-review/final-review.ts
intervention-progress/reports/indicator-report-target.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/modals/activity-dialog/activity-item-row.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicator.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch23854] Placeholders tweaks and standardization

[ch23854] Placeholders tweaks and standardization

---

common/styles/info-element-styles.ts

[ch23858] Overview components style tweaks

[ch23858] Overview components style tweaks

---

intervention-results/supply-agreement/supply-agreement.ts

[ch23811] Supply Agreement/ Add optional field 'Unicef Product Number'

[ch23811] Supply Agreement/ Add optional field 'Unicef Product Number'

---

common/layout/are-you-sure.ts
common/mixins/component-base-mixin.ts
common/mixins/repeatable-data-sets-mixin.ts
intervention-actions/intervention-actions.ts
intervention-attachments/intervention-attachment-dialog.ts
intervention-details/document-details/document-details.ts
intervention-details/geographical-coverage/grouped-locations-dialog.ts
intervention-details/partner-details/partner-info.ts
intervention-details/unicef-details/unicef-details.ts
intervention-management/fund-reservations/update-fr-numbers.ts
intervention-management/risks/risk-dialog.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.ts
intervention-tabs.ts
intervention-timing/activity-timeframes/activity-timeframes.ts

[ch23781] Add second language (romanian).

[ch23781] Add second language (romanian).

---

intervention-management/final-review/final-review-popup.ts
intervention-management/programmatic-visits/programmatic-visits.ts
intervention-results/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch23884] Wrong toast text

---

common/components/comments/comments-dialog.ts
intervention-results/results-structure/results-structure.ts

[ch23911] Style issues: Black outline and # of comments badge cut off

[ch23911] Style issues: Black outline and # of comments badge cut off

---

intervention-overview/fund-reservations-display/fund-reservations-display.ts
intervention-results/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/results-structure.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch23154] Expose etools-currency-mixin functionality in an es6 module also

[ch23154] Expose etools-currency-mixin functionality in an es6 module also

---

utils/intervention-endpoints.ts

[ch23549] Update Results export button url to v3

[ch23549] Update Results export button url to v3

---

common/components/comments/comments-mixin.ts
intervention-results/results-structure/pd-indicator.ts
intervention-timing/reporting-requirements/partner-reporting-requirements.ts

[ch23431]Border width inconsistency when Comment Mode is enabled:

[ch23431]Border width inconsistency when Comment Mode is enabled

---

intervention-management/review-and-sign/review-and-sign.ts

[ch24176]Signatures & Dates: Signed PD/SPD file not reset on cancel

[ch24176]Signatures & Dates: Signed PD/SPD file not reset on cancel

---

intervention-management/risks/risk-dialog.ts

[ch24148] Console error when editing risk

[ch24148] Console error when editing risk

---

common/styles/shared-styles-lit.ts
intervention-details/unicef-details/unicef-details.ts
intervention-management/programmatic-visits/programmatic-visits.ts
intervention-management/review-and-sign/review-and-sign.ts
intervention-results/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/modals/activity-dialog/acivity-items-table.styles.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/modals/activity-dialog/activity-item-row.ts
intervention-results/results-structure/modals/activity-dialog/activity-items-table.ts
intervention-results/results-structure/modals/activity-dialog/activity-timeframes.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.ts
utils/common-methods.ts

[ch24038] Forms should be navigable using TAB

[ch24038] Forms should be navigable using TAB

---

intervention-results/budget-summary/budget-summary.ts

[ch24258] UI - Merge '% Partner Contrib' with 'Total CSO Contrib'

[ch24258] UI - Merge '% Partner Contrib' with 'Total CSO Contrib'

---

intervention-review/intervention-review.ts
intervention-tabs.ts

[ch24246]Show Review tab in all PD statuses

[ch24246]Show Review tab in all PD statuses

---

intervention-timing/timing-overview/timing-overview.ts
utils/date-utils.ts

[ch24245] Date first sent to partner is one day less than actual (localization)

[ch24245] Date first sent to partner is one day less than actual (localization)

---

intervention-review/intervention-review.ts

[ch24287]Review Tab: set permission matrix

[ch24287]Review Tab: set permission matrix

---

intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.styles.ts
intervention-results/results-structure/results-structure.ts

[ch24198] Edit/Delete actions should show up when hovering any area of the row

[ch24198] Edit/Delete actions should show up when hovering any area of the row

---

common/components/intervention/pd-termination.ts
intervention-attachments/intervention-attachment-dialog.ts
intervention-management/amendments/add-amendment-dialog.ts
intervention-management/review-and-sign/review-and-sign.ts

[ch24398] ePD: Unable to attach .text and .jpeg extension files.

[ch24398] ePD: Unable to attach .text and .jpeg extension files.

---

assets/i18n/ar.json
assets/i18n/en.json

ch24357] ePD: Action button shows as "SEND TO PARTENER"

ch24357] ePD: Action button shows as "SEND TO PARTENER"

---

intervention-timing/reporting-requirements/srr/add-edit-special-rep-req.ts

[ch24415] Special Reporting Requirements dialog not opening the second time

[ch24415] Special Reporting Requirements dialog not opening the second time

---

intervention-details/technical-guidance-capacity/technical-guidance.ts

[ch24443] ePD- No word limitation for Technical guidance, capacity development, other partners involved, other information fields.

[ch24443] ePD- No word limitation for Technical guidance, capacity development, other partners involved, other information fields.

---

intervention-details/unicef-details/unicef-details.ts

[ch24435] Unable to deselect the value in the unicef budget owner

[ch24435] Unable to deselect the value in the unicef budget owner

---

intervention-details/gender-equity-rating/gender-equity-rating.ts

[ch24441] ePD- No word limitation for Gender Narrative, Sustainability narrative, equity narrative fields.

[ch24441] ePD- No word limitation for Gender Narrative, Sustainability narrative, equity narrative fields.

---

intervention-details/document-details/document-details.ts

[ch24438] ePD- No word limitation for Context, Implementation strategy, Partner non financial contribution fields only implemented for title fields.

[ch24438] ePD- No word limitation for Context, Implementation strategy, Partner non financial contribution fields only implemented for title fields.

---

assets/i18n/ar.json
assets/i18n/en.json

[ch24531] ePD: Correct "Cash Transfered" to "Cash Transferred"

[ch24531] ePD: Correct "Cash Transfered" to "Cash Transferred"

---

intervention-management/fund-reservations/fund-reservations.ts

[ch24479] ePD: Entering invalid FR Number displays an error message containing technical details

[ch24479] ePD: Entering invalid FR Number displays an error message containing technical details

---

intervention-review/intervention-review.ts
utils/date-utils.ts

[ch24283] moment.js is deprecated, time for an alternative

[ch24283] moment.js is deprecated, time for an alternative

---

common/styles/shared-styles-lit.ts
intervention-attachments/attachments-list.ts
intervention-management/amendments/pd-amendments.ts
intervention-management/final-review/final-review.ts
intervention-management/review-and-sign/review-and-sign.ts
intervention-overview/fund-reservations-display/fund-reservations-display.ts
intervention-overview/intervention-overview.ts
intervention-results/results-structure/modals/indicator-dialog/non-cluster-indicator.ts
intervention-results/results-structure/results-structure.ts
intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
utils/common-methods.ts

[ch24448]Fix tab navigation on elements

[ch24448]Fix tab navigation on elements

---

common/layout/etools-form-element-wrapper.ts
common/layout/icons-actions.ts
common/layout/status/intervention-report-status.ts

[ch24338]Migrate remaining `intervention-tab-pages` PolymerElements to LitElement

[ch24338]Migrate`common/layout` folder to LitElement

---

common/mixins/common-mixin.ts
common/mixins/endpoints-mixin.ts
common/mixins/pagination-mixin.ts
common/mixins/utils-mixin.ts

[ch24338] Migrate remaining `intervention-tab-pages` PolymerElements to LitElement

[ch24338] Migrate common mixins to LitElement

---

intervention-reports/intervention-reports.ts

[ch24338]Migrate intervention-report to Lit Element

[ch24338]Migrate intervention-report to Lit Element

---

common/layout/etools-form-element-wrapper.ts
intervention-progress/intervention-progress.ts
intervention-progress/layout/etools-progress-bar.ts
intervention-progress/layout/etools-ram-indicators.ts
intervention-progress/reports/indicator-report-target.ts
intervention-progress/styles/pmp-icons.ts

[ch24338]Migrate remaining `intervention-tab-pages` PolymerElements to LitElement

[ch24338]Migrate intervention-progress to Lit Element

---

intervention-tabs.ts

[ch24430] ePD: "Unicef" should be "UNICEF" across entire application

[ch24430] ePD: "Unicef" should be "UNICEF" across entire application

---

intervention-review/intervention-review.ts

[ch24285] Review tab is not rendered

[ch24285] Review tab is not rendered

---

intervention-management/review-and-sign/review-and-sign.ts

[ch24524]Fix auth off. & unicef users being cleared after page refresh

---

intervention-timing/reporting-requirements/mixins/reporting-requirements-common-mixin.ts

[ch24534] UI not updated after edit on dates for QPRs and HRs

[ch24534] UI not updated after edit on dates for QPRs and HRs

---

common/styles/shared-styles-lit.ts
intervention-overview/intervention-overview.ts

[ch24448]Change focus style

---

intervention-details/gender-equity-rating/gender-equity-rating.ts

[ch24161]Required fields for transition to Review state not marked as required in the UI

[ch24161]Connect gender-equity text fields to permission matrix

---

intervention-progress/intervention-progress.ts
intervention-reports/intervention-reports.ts

[ch24723]Do not do PRP requests for Draft PD

---

intervention-details/unicef-details/pdUnicefDetails.models.ts
intervention-details/unicef-details/unicef-details.ts

[ch24439]Remove Doc Type from Unice Details section

---

intervention-attachments/intervention-attachment-dialog.ts

[ch24733] Unnecessary placeholder in Attachment dialog

[ch24733] Unnecessary placeholder in Attachment dialog

---

common/styles/shared-styles-lit.ts
intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
intervention-timing/reporting-requirements/qpr/quarterly-reporting-requirements.ts

[ch24798]Change focused style for these buttons when navigating using tab

[ch24798]Change focused style for these buttons when navigating using tab

---

common/layout/page-content-header/intervention-page-content-header.ts
common/styles/grid-layout-styles-lit.ts
common/styles/repeatable-data-sets-styles.ts
intervention-details/details-overview/details-overview.ts
intervention-management/fund-reservations/update-fr-numbers.ts
intervention-progress/intervention-progress.ts

[ch24690] Drop the use of iron-flex-layout  (Drop use of flex basis)

[ch24690] Drop the use of iron-flex-layout (Drop use of flex basis)

---

intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicator.ts

[ch24676] [etools-data-table] Replace CSS mixins with CSS Shadow Parts

[ch24676] fixed result structures hover styles

---

intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
intervention-timing/reporting-requirements/hr/humanitarian-reporting-req-unicef.ts
intervention-timing/reporting-requirements/mixins/reporting-requirements-common-mixin.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
intervention-timing/reporting-requirements/qpr/quarterly-reporting-requirements.ts
intervention-timing/reporting-requirements/srr/add-edit-special-rep-req.ts
intervention-timing/reporting-requirements/srr/special-reporting-requirements.ts
utils/request-helper.ts

[ch24804] [Refactor] Simplify how modals are used,  replace remaining deprecated code with openDialog method

[ch24804] [Refactor] Simplify how modals are used,  replace remaining deprecated code with openDialog method

---

intervention-results/results-structure/pd-indicators.ts

[ch24676] [Fix] Replaced etools-data-table css mixins with CSS Shado Parts

[ch24676] [Fix] Replaced etools-data-table css mixins with CSS Shado Parts

---

common/components/comments/comments-mixin.ts

[ch24851] Console error on Settings

[ch24851] Console error on Settings

---

intervention-progress/intervention-progress.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicator.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.ts

[ch24676] [etools-data-table] Replace CSS mixins with CSS Shadow Parts

[ch24676] [etools-data-table] Replace CSS mixins with CSS Shadow Parts

---

common/styles/shared-styles-lit.ts

[ch24869] Focus style issues on intervention tab pages - Safari browser

[ch24869] Focus style issues on intervention tab pages - Safari browser

---

common/styles/shared-styles-lit.ts
intervention-details/document-details/document-details.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/modals/activity-dialog/activity-timeframes.ts

[ch24812]Do not show focused style on click/select timeframe+ other fixes

---

intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/results-structure.ts

[ch24957]Add `... show more` link to Results Structure/RAM indicators

---

intervention-results/results-structure/modals/activity-dialog/activity-timeframes.ts

[ch24812]focus-visible polyfill  for Safari

---

common/mixins/endpoints-mixin-lit.ts

[ch24836] Console error if you refresh on Progress and Reports tab

[ch24836] Console error if you refresh on Progress and Reports tab

---

common/styles/shared-styles-lit.ts
intervention-results/results-structure/modals/activity-dialog/activity-timeframes.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts

[ch25019] Remove the black border present at click on elements

[ch25019] Remove the black border present at click on elements

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-timing/intervention-dates/intervention-dates.ts

[ch23578]Show FE warning only for Partner Rep Requirements on start/end dates edits

---

intervention-timing/reporting-requirements/partner-reporting-requirements.ts

[ch25155] [Accessibility]: Navigation with tab on Partner reporting requirements

[ch25155] [Accessibility]: Navigation with tab on Partner reporting requirements

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch25179]Relabel Supply Agreement

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-details/document-details/document-details.ts
intervention-tabs.ts

[ch25176]Relabel IP Accepted flag&localize

---

intervention-details/document-details/document-details.ts
intervention-details/gender-equity-rating/gender-equity-rating.ts
intervention-details/technical-guidance-capacity/technical-guidance.ts

[ch25331] In Details tab show by default 3 rows for textarea controls.

[ch25331] In Details tab show by default 3 rows for textarea controls

---

intervention-management/programmatic-visits/programmatic-visits.ts

[ch25286] Unsaved Planned Visit disappears on window width decrease

[ch25286] Unsaved Planned Visit disappears on window width decrease

---

intervention-details/document-details/document-details.ts
intervention-details/gender-equity-rating/gender-equity-rating.ts
intervention-details/technical-guidance-capacity/technical-guidance.ts
utils/common-methods.ts

[ch25331] In Details tab show by default 3 rows for textarea controls.

[ch25331] In Details tab show by default 3 rows for textarea controls.

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-management/financial/financial-component.ts

[ch24259]HQ Contrib input field fix

---

intervention-attachments/prc-document/prc-document.ts
intervention-metadata/other/other.models.ts
intervention-metadata/other/other.ts
intervention-strategy/document-details/document-details.ts
intervention-strategy/gender-equity-rating/gender-equity-rating.ts
intervention-strategy/technical-guidance-capacity/technical-guidance.ts

[ch25352] ePD  / PMP reorganize fields

[ch25352] ePD  / PMP reorganize fields

---

intervention-info/intervention-implementation-status.ts
intervention-info/intervention-info.ts
intervention-info/intervention-monitoring-activities.ts
intervention-info/intervention-progress.ts
intervention-info/intervention-reports.ts
intervention-info/intervention-summary.ts
intervention-info/layout/etools-ram-indicators.ts
utils/common-methods.ts

[ch25410] RAM Indicators missing from Progress/Results Reported tab

[ch25410] RAM Indicators missing from Progress/Results Reported tab

---

intervention-results/non-financial-contribution/non-financial-contribution.ts
intervention-strategy/document-details/document-details.ts

[ch25446] Console error on PD details - Strategy tab

[ch25446] Console error on PD details - Strategy tab

---

common/layout/etools-tabs.ts
intervention-info/intervention-monitoring-activities.ts
intervention-results/results-structure/cp-output-level.ts
intervention-results/results-structure/modals/activity-dialog/activity-item-row.ts
intervention-results/results-structure/modals/activity-dialog/activity-items-table.ts
intervention-results/results-structure/modals/activity-dialog/activity-timeframes.ts
intervention-results/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts
intervention-results/results-structure/pd-activities.ts
intervention-results/results-structure/pd-indicators.ts
intervention-results/results-structure/results-structure.ts
intervention-tabs.ts
intervention-timing/reporting-requirements/partner-reporting-requirements.ts
utils/common-methods.ts

[ch25433]Accessible Info tab

---

common/styles/required-field-styles.ts
common/styles/shared-styles-lit.ts

[ch25298] Add slot for info icon to etools-dropdown's label

[ch25298] Add slot for info icon to etools-dropdown's label

---

intervention-results/results-structure/results-structure.ts

[ch25565]Results Structure -View chips style update

---

common/layout/etools-tabs.ts
intervention-tabs.ts

[ch25432] Fix 2 tabs underlined at the same time

---

intervention-info/intervention-progress.ts
utils/date-utils.ts

[ch25684] PMP: PROGRESS tab show incorrect "PD Duration" and "Cash Transfered" values

[ch25684] PMP: PROGRESS tab show incorrect "PD Duration" and "Cash Transfered" values

---

common/components/cancel/cancel-justification.ts
common/layout/status/etools-status.ts
common/styles/shared-styles-lit.ts
intervention-results/hq-contribution/hq-contribution.ts
intervention-timing/activity-timeframes/activity-timeframes.styles.ts
intervention-timing/activity-timeframes/activity-timeframes.ts

[ch25651]Fixes for RTL page direction

---

common/components/comments/comments-mixin.ts
common/layout/etools-tabs.ts
intervention-results/results-structure/results-structure.ts

[ch25765]Fix z-index contest(tab underline overlaps dropdown)

---

intervention-tabs.ts

[ch25803] PD status informative chip (ex 'Sent to Partner') looks too much like a button

---

intervention-actions/intervention-actions.ts

[ch25772] Arabic style issues #1

[ch25772] Arabic style issues #1

---

intervention-metadata/fund-reservations/update-fr-numbers.ts
intervention-results/hq-contribution/hq-contribution.ts
intervention-results/results-structure/results-structure.styles.ts
intervention-timing/activity-timeframes/activity-timeframes.ts

[ch25777] Arabic style issues #2

[ch25777] Arabic style issues #2

---

common/constants.ts
common/selectors.ts
intervention-info/intervention-implementation-status.ts
intervention-info/intervention-info.ts
intervention-info/intervention-monitoring-activities.ts
intervention-tabs.ts

[ch25901] Check tabs permissions

---

intervention-tabs.ts

[ch25935]Cannot add new PD/SPD

---

intervention-results/results-structure/modals/activity-dialog/activity-item-row.ts

[ch25801] New field structure for Input level from PD activities

[ch25801] New field structure for Input level from PD activities

---

common/layout/page-content-header/intervention-page-content-header.ts

[ch25920] Proper alignment for components in page header

[ch25920] Proper alignment for components in page header

---

intervention-results/hq-contribution/hq-contribution.ts

[ch25940] HQ Contribution 'red' informative message to be shown only for unicef users

[ch25940] HQ Contribution 'red' informative message to be shown only for unicef users

---

common/layout/etools-tabs.ts

[ch25923] Fix UI for tabs on smaller screen width

[ch25923] Fix UI for tabs on smaller screen width

---

intervention-strategy/gender-equity-rating/gender-equity-rating.ts

[ch25942] Adjust readonly UI for 'Gender, Equity, sustainability' card

[ch25942] Adjust readonly UI for 'Gender, Equity, sustainability' card

---

common/constants.ts
intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts

[ch25948]Default selection for supply item should be UNICEF

---

intervention-results/results-structure/modals/activity-dialog/acivity-items-table.styles.ts
intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-results/results-structure/modals/activity-dialog/activity-item-row.ts
intervention-results/results-structure/modals/activity-dialog/activity-items-table.ts

[ch25949] Tweak UI for PD Activity dialog

[ch25949] Tweak UI for PD Activity dialog

---

intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts

[ch25921]etools-date-time tweak

---

intervention-results/budget-summary/budget-summary.ts

[ch25799] Allow Supply Contribution to be made by Partner also

[ch25799] Allow Supply Contribution to be made by Partner also- show partner percentage next to Total Partner Contrib

---

common/managementDocument.selectors.ts
intervention-metadata/intervention-metadata.ts
intervention-metadata/review-and-sign/review-and-sign.ts
intervention-timing/intervention-timing.ts

[ch25946]Connect to permissions.view

---

common/components/intervention/start-review.ts
common/constants.ts
intervention-results/supply-agreement/supply-agreement-dialog.ts
intervention-results/supply-agreement/supply-agreement.ts
intervention-review/general-review-information/general-review-information.ts
intervention-review/review.const.ts

[ch26004] Display drop-down value without square brackets

[ch26004] Display drop-down value without square brackets

---

intervention-results/supply-agreement/supply-agreement.ts

[ch26026]If Provider By: Partner, hide the UNICEF Product Number

---

intervention-strategy/geographical-coverage/geographical-coverage.ts

[ch26245]Fix console err

---

intervention-progress/monitoring-visits-list.ts

[ch26247]Misplaced loading screen on Progress - Monitoring Activities

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-metadata/details-overview/details-overview.ts
intervention-timing/timing-overview/timing-overview.ts
intervention-workplan/budget-summary/budget-summary.ts

[ch25944] A more indicative style for readonly cards

[ch25944] A more indicative style for readonly cards

---

intervention-metadata/financial/financial-component.ts

[ch26236]Issues saving Cash Transfer Modalities

---

intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts

[ch26218] Restyle datepicker control

[ch26218] Restyle datepicker control

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-workplan/supply-agreement/supply-agreement.ts

[ch26313] Tooltip for upload supply contribution

[ch26313] Tooltip for upload supply contribution

---

common/mixins/utils-mixin.ts

[ch26119] Progress report in eTools does not show percentages correctly

[ch26119] Progress report in eTools does not show percentages correctly

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
common/components/intervention/start-review.ts

[ch26325] Label of card for Review Type change

[ch26325] Label of card for Review Type change

---

intervention-strategy/gender-equity-rating/gender-equity-rating.ts

[ch26312] Gender, equity, sustainability card can enter lot of text in each field but system shows very few lines

[ch26312] Gender, equity, sustainability card can enter lot of text in each field but system shows very few lines

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-metadata/details-overview/details-overview.ts
intervention-metadata/details-overview/interventionOverview.models.ts

[ch26311] Metadata read only card show dates of assessments

[ch26311] Metadata read only card show dates of assessments

---

common/mixins/uploads-mixin.ts
intervention-attachments/prc-document/prc-document.ts
intervention-metadata/review-and-sign/review-and-sign.ts
intervention-timing/intervention-dates/intervention-dates.ts

[ch26161] Verify the correct use of UploadMixin

[ch26161] Verify the correct use of UploadMixin

---

assets/i18n/en.json
assets/i18n/ro.json
common/layout/export-intervention-data.ts
intervention-actions/intervention-actions.constants.ts
intervention-tabs.ts
intervention-workplan/results-structure/results-structure.ts

[ch23616] Move result export to the top of the page like the list export.

[ch23616] Move result export to the top of the page like the list export.

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-actions/intervention-actions.constants.ts
intervention-actions/intervention-actions.ts

[ch26322] Review button change text and popup message

[ch26322] Review button change text and popup message

---

intervention-workplan/hq-contribution/hq-contribution.ts

[ch26392] HQ contribution red text - show only when in edit mode

[ch26392] HQ contribution red text - show only when in edit mode

---

intervention-actions/intervention-actions.styles.ts
intervention-actions/intervention-actions.ts

[ch26380] Issue with 'Export actions' not showing up under the Export btn & style issue

[ch26380] Issue with 'Export actions' not showing up under the Export btn & style issue

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json

[ch26396] Add 'For legacy PDs only' to the 'PRC Review Document' label from Attachments tab

[ch26396] Add 'For legacy PDs only' to the 'PRC Review Document' label from Attachments tab

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-metadata/review-and-sign/review-and-sign.ts
intervention-tabs.ts

[ch26415]Customizable title for the cancel-justification component

---

intervention-metadata/details-overview/details-overview.ts
intervention-workplan/effective-efficient-programme-mgmt/activity-dialog.ts

[ch26461]Currency missing from EEPM, Placeholder missing for PSEA date

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicators.ts

[ch26469]Results Structure UI tweak

---

intervention-metadata/amendments/pd-amendments.ts

[ch26659] Amendment PDs should appear in the PD list after they are created

[ch26659] Amendment PDs should appear in the PD list after they are created

---

common/actions/officers-reviews.ts
common/components/intervention/review-checklist-popup.ts
common/reducers/officers-reviews.ts
common/types/store.types.ts
intervention-review/reviews-list/reviews-list.ts
intervention-tabs.ts

[ch26683]Fix navigating between pd reviews & renames

---

intervention-review/overall-approval/overall-approval.ts

[ch26699]Even out the padding in components on Review tab

---

common/types/store.types.ts
intervention-metadata/review-and-sign/review-and-sign.ts
intervention-tabs.ts

[ch26749]Fix Signature data not saving

---

common/components/comments/comment.ts
common/components/comments/comments-dialog.ts
common/components/comments/comments-mixin.ts
intervention-tabs.ts

[ch26851]Fix comments in incognito

---

intervention-actions/intervention-actions.ts

[ch26697] After hitting Start Review you should be redirected to 'Review' tab

[ch26697] After hitting Start Review you should be redirected to 'Review' tab

---

intervention-strategy/gender-equity-rating/gender-equity-rating.ts
intervention-strategy/gender-equity-rating/rating-instructions.ts

[ch25943] Info icons for 'Gender,Equity,Sustainability' Ratings

[ch25943] Info icons for 'Gender,Equity,Sustainability' Ratings

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-metadata/other/other.models.ts
intervention-metadata/other/other.ts

[ch26798] New Field Activation Protocol

[ch26798] New Field Activation Protocol

---

common/layout/export-intervention-data.ts
intervention-actions/intervention-actions.constants.ts
utils/intervention-endpoints.ts

[ch26691] Create PD HTML Template for export to PDF.

[ch26691] Create PD HTML Template for export to PDF.

---

intervention-workplan/supply-agreement/supply-agreement.ts

[ch26883] Help text on Supply contribution card missing

[ch26883] Help text on Supply contribution card missing

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json

[ch26906] On Cancel action change the default text

[ch26906] On Cancel action change the default text

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-actions/intervention-actions.constants.ts
intervention-actions/intervention-actions.ts
intervention-tabs.ts

[ch26917] In Review state for budget owner the action "Sign" should be renamed to  "Recommend for Approval"

[ch26917] In Review state for budget owner the action "Sign" should be renamed to  "Recommend for Approval"

---

intervention-workplan/results-structure/results-structure.ts

[ch26909] Add tooltip on "Add CP Output" plus button on the results card. The tooltip should say "Add CP Output" similar to supply upload

[ch26909] Add tooltip on "Add CP Output" plus button on the results card. The tooltip should say "Add CP Output" similar to supply upload

---

intervention-attachments/attachments-list/intervention-attachment-dialog.ts

[ch26913] Allow Excel uploads in attachments

---

intervention-actions/accept-for-partner.ts
intervention-actions/intervention-actions.ts
intervention-tabs.ts

[ch26918]Accept of behalf, Ask for submission_date only if empty

---

intervention-review/intervention-review.ts

[ch27036]Issue with Review sections visible on UI when  `No Review Required`

---

intervention-timing/reporting-requirements/partner-reporting-requirements.ts

[ch27016]Fix console err

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
common/layout/export-intervention-data.ts
intervention-actions/intervention-actions.constants.ts
utils/intervention-endpoints.ts

[ch26693] PD Exports to excel csv and pdf

[ch26693] PD Exports to excel csv and pdf

---

intervention-actions/intervention-actions.styles.ts
intervention-actions/intervention-actions.ts

[ch27032] Different results on split btn click

---

intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts

[ch27115] Console error when trying to delete Final Quarterly Progress Report

[ch27115] Console error when trying to delete Final Quarterly Progress Report

---

intervention-progress/intervention-results-reported.ts
intervention-strategy/geographical-coverage/sites-widget/map-mixin.ts
intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-workplan/results-structure/modals/pd-output-dialog.ts

[ch27130] Fix TsLint errors

---

intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch25800][Intermittent] 0.00 totals displayed after adding/editing Result Structure PD Activities

---

common/components/activity/activity-item-row.ts
common/components/activity/activity-items-table.styles.ts
common/components/activity/activity-items-table.ts

[ch27427] [Usability]PD Activity - Delete row btn 'x' is too close to Unicef Cash

[ch27427] [Usability]PD Activity - Delete row btn 'x' is too close to Unicef Cash

---

common/components/activity/get-total.helper.ts
intervention-workplan/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-workplan/results-structure/pd-activities.ts

[ch27436]Fix number formatting

---

intervention-workplan/results-structure/modals/cp-output-dialog.ts

[ch27443] Display specific error message on add CP Output failure

[ch27443] Display specific error message on add CP Output failure

---

intervention-strategy/document-details/document-details.ts
intervention-workplan/non-financial-contribution/non-financial-contribution.ts

[ch27475] Save+ Cancel buttons Alignment inconsistency

[ch27475] Save+ Cancel buttons Alignment inconsistency

---

common/components/activity/activity-item-row.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/results-structure.ts

[ch26841]Style fix after using lit content-panel

---

intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicator.ts
intervention-workplan/results-structure/results-structure.styles.ts

[ch27438]Adjust the line height for indicators with long titles in Results Structure

---

common/components/activity/activity-items-table.ts

[ch27492] [Intermittent]Display issues when editing an Activity with a long items list

[ch27492] [Intermittent]Display issues when editing an Activity with a long items list

---

intervention-timing/programmatic-visits/programmatic-visits.ts

[ch27511] Programmatic Visits section - Display the entire label when there is enough space

[ch27511] Programmatic Visits section - Display the entire label when there is enough space

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-workplan/results-structure/pd-indicator.ts
intervention-workplan/results-structure/pd-indicators.ts
intervention-workplan/results-structure/results-structure.ts

[ch27493]Deactivate indicator tweaks

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-timing/programmatic-visits/programmatic-visits.ts
intervention-workplan/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-workplan/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts

[ch27521]View btn for readonly Effective and Efficient Prgm Mgmt items

---

intervention-timing/programmatic-visits/programmatic-visits.ts

[ch26841] Migrate reusable components to LitElement

[ch26841] Migrate reusable components to LitElement

---

intervention-workplan/effective-efficient-programme-mgmt/activity-dialog.ts
utils/utils.ts

[ch27630] Effective and Efficient PM: Error on Edit Activity with Input-level items

[ch27630] Effective and Efficient PM: Error on Edit Activity with Input-level items

---

intervention-metadata/amendments/pd-amendments.ts

[ch27624] Clickable placeholder that leads to null.htm being downloaded

---

intervention-metadata/other/other.models.ts
intervention-metadata/other/other.ts

[ch26915]Connect currency field to document_currency permission

---

intervention-metadata/other/other.models.ts

[ch26915]Card editability fix

---

common/constants.ts
intervention-actions/intervention-actions.constants.ts
intervention-actions/intervention-actions.ts
intervention-tabs.ts

[ch27848]Export results-link visibility

---

intervention-progress/intervention-reports.ts

[ch27996]Reusable component migration fixes

---

intervention-metadata/details-overview/details-overview.ts
intervention-strategy/document-details/document-details.ts
intervention-strategy/gender-equity-rating/gender-equity-rating.ts
intervention-strategy/geographical-coverage/geographical-coverage.ts
intervention-strategy/risks/risks.ts
intervention-timing/reporting-requirements/partner-reporting-requirements.ts
intervention-timing/timing-overview/timing-overview.ts
intervention-workplan/budget-summary/budget-summary.ts
intervention-workplan/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-workplan/non-financial-contribution/non-financial-contribution.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts
intervention-workplan/results-structure/pd-indicators.ts

[ch27985] Integrate info-icon-tooltip from etools-modules-common in etools-info-tooltip package

[ch27985] Integrate info-icon-tooltip from etools-modules-common in etools-info-tooltip package

---

intervention-timing/intervention-dates/intervention-dates.ts

[ch28118] Tooltips icons for Start/End Date inconsistencies missing from Programme Document dates section

[ch28118] Tooltips icons for Start/End Date inconsistencies missing from Programme Document dates section

---

intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts

[ch27978] Remove Cluster Indicator toggle when entering new indicators

[ch27978] Remove Cluster Indicator toggle when entering new indicators

---

intervention-timing/reporting-requirements/hr/hru-list.ts
intervention-timing/reporting-requirements/hr/humanitarian-reporting-req-unicef.ts

[ch28032] Pagination for Humanitarian Reports not working

[ch28032] Pagination for Humanitarian Reports not working

---

intervention-review/intervention-review.ts

[ch27527] Explicitly set notification flag color

---

intervention-metadata/review-and-sign/review-and-sign.ts

[ch28302] Lit migration upload component: Signature &Dates issues

[ch28302] Lit migration upload component: Signature &Dates issues

---

intervention-metadata/amendments/add-amendment-dialog.ts

[ch28329] Add Amendment: Warning texts when selecting amendment type missing from ePD

[ch28329] Add Amendment: Warning texts when selecting amendment type missing from ePD

---

intervention-strategy/geographical-coverage/grouped-locations-dialog.ts

[ch28330]Adapt to locations 3.2

---

intervention-workplan/results-structure/cp-output-level.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicator.ts
intervention-workplan/results-structure/results-structure.ts

[ch28373]Automatic Numbering of Results in ePD

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-actions/intervention-actions.constants.ts
intervention-actions/intervention-actions.ts
intervention-review/intervention-review.ts

[ch28260] Ability for PRC Secretary to send back to Programme Officer

---

common/components/comments/comment.ts

[ch28837] Change name of date field of comments

---

common/components/comments/comments-mixin.ts
intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts
intervention-workplan-editor/editor-utils/types.ts
intervention-workplan-editor/time-intervals/time-intervals.ts
utils/intervention-endpoints.ts

[ch28850]Editor -use time-intervals comp, validate/auto fill in item amounts, bug fixes

---

intervention-timing/reporting-requirements/partner-reporting-requirements.ts

[ch28753] PRP: remove/hide Humanitarian Reports - Cluster from PMP and PRP

[ch28753] PRP: remove/hide Humanitarian Reports - Cluster from PMP and PRP

---

assets/i18n/en.json
intervention-workplan/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-workplan/results-structure/display-controls.ts
intervention-workplan/results-structure/results-structure.ts
intervention-workplan/results-structure/styles/results-structure.styles.ts

[ch28849] Move view controls outside the card

---

common/layout/export-intervention-data.ts
common/layout/page-content-header/intervention-page-content-header.ts
intervention-actions/intervention-actions.ts
intervention-tabs.ts

[ch28845] Toggling between comments mode

[ch28845] Toggling between comments mode

---

intervention-tabs.ts

[ch28999] [Editor]Export dropdown overlay issue on Results Structure editor page

[ch28999] [Editor]Export dropdown overlay issue on Results Structure editor page

---

intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch29072]Fix lingering validations&values reset after save->invalid data->cancel

---

intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch29082]Fix border for delete activity item cell

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-metadata/other/other.models.ts
intervention-metadata/other/other.ts

[ch29008]Confidential field

---

intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts

[ch28850]Arrow navigation to delete activity item

---

common/components/comments-panels/comments-list/comments-group.ts
common/components/comments-panels/comments-list/comments-list.ts
common/components/comments-panels/comments-list/comments-panel-header.ts
common/components/comments-panels/comments-panels.ts
common/components/comments-panels/common-comments.styles.ts
common/components/comments/comments-mixin.ts
intervention-tabs.ts

[ch28848] Add fixes and improvements to comments panels

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts
intervention-workplan-editor/intervention-workplan-editor.ts
intervention-workplan/budget-summary/budget-summary.ts

[ch29227]Editor tweaks 

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts
intervention-workplan-editor/editor-utils/editor-hover-styles.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch29136]Editor- reduce empty space & adapt arrow navigation to changes

---

common/components/activity/activity-item-row.ts
common/components/activity/activity-items-table.ts
intervention-workplan-editor/time-intervals/time-intervals.ts
intervention-workplan/results-structure/cp-output-level.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicator.ts
intervention-workplan/results-structure/pd-indicators.ts
intervention-workplan/results-structure/results-structure.ts
intervention-workplan/results-structure/styles/ativities-and-indicators.styles.ts
intervention-workplan/results-structure/styles/results-structure.styles.ts

[ch29293][New UI] Refactor Result Structure Part 2

---

intervention-workplan-editor/editor-table.ts

[ch29350]Move focus after add btn click

---

intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/editor-hover-styles.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts
intervention-workplan-editor/time-intervals/time-intervals.ts

[ch29406]Fix tab nav at end of activity item row

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch29292]Fix cancelling pd output or activity after add new one of them & tweaks

---

intervention-workplan/intervention-workplan.ts
intervention-workplan/results-structure/cp-output-level.ts
intervention-workplan/results-structure/display-controls.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicator.ts
intervention-workplan/results-structure/pd-indicators.ts
intervention-workplan/results-structure/results-structure.ts
intervention-workplan/results-structure/styles/ativities-and-indicators.styles.ts
intervention-workplan/results-structure/styles/results-structure.styles.ts

[ch29426] Ui improvements for result structure

---

intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch29431]Preserve focus when entering edit mode by pressing enter on a field

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts

[ch29433]Escape moves focus to unexpected cell

---

intervention-workplan/results-structure/display-controls.ts
intervention-workplan/results-structure/results-structure.ts

[ch29442]  Show Inactive should show up only when there are inactive items

---

intervention-workplan/results-structure/results-structure.ts

[ch29449] Expand all content when entering comment mode

---

common/components/comments/comments-mixin.ts

[ch29445]Fix Comment mode does not emphasize all commentable elements

---

common/components/comments/comments-mixin.ts

[ch29445]Fix comment mode border color not updating after comment add

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/editor-hover-styles.ts

[ch29454]Cancel hover when in comment mode

---

intervention-workplan-editor/editor-utils/activities-mixin.ts

[ch29427] [Editor] Time Periods component - readonly mode is broken

[ch29427] [Editor] Time Periods component - readonly mode is broken

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts

[ch29403] [Editor]Add ellipsis to cut off text

[ch29403] [Editor]Add ellipsis to cut off text

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts

[ch29455] [Editor]Add max-length counter to text fields

[ch29455] [Editor]Add max-length counter to text fields

---

common/layout/page-content-header/intervention-page-content-header.ts
intervention-actions/intervention-actions.styles.ts

[ch29444] Make PD header sticky

[ch29444] Make PD header sticky

---

intervention-workplan-editor/editor-table.ts

[ch29508] [Editor] Correct Partner tooltip position

[ch29508] [Editor] Correct Partner tooltip position

---

intervention-workplan/results-structure/results-structure.ts

[ch29496] Error when entering comment mode while logged as Partner User

[ch29496] Error when entering comment mode while logged as Partner User

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/editor-hover-styles.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch29472][Editor] Handle display of unassociated PD Outputs created by Partners

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts
intervention-workplan-editor/editor-utils/types.ts

[ch29472]PD Output assignement to CP Output on Editor page

---

intervention-workplan-editor/editor-utils/activities-mixin.ts

[ch29473][Editor]Time Periods selection dialog should open on enter

[ch29473][Editor]Time Periods selection dialog should open on enter

---

intervention-workplan-editor/editor-utils/activity-item-mixin.ts

[ch29495]Only one decimal for n of units

---

intervention-workplan-editor/editor-utils/activity-item-mixin.ts

[ch29447]Tooltip for code column

---

intervention-workplan/results-structure/pd-indicator.ts

[ch29426] Don't show decimals in indicators table if they doesn't exist

---

intervention-metadata/other/other.models.ts
intervention-metadata/other/other.ts

[ch29443] Confidential field is supposed to be boolean

[ch29443] Confidential field is supposed to be boolean

---

common/components/comments-panels/comments-list/comments-list.ts
common/components/comments-panels/comments-panels.ts
common/components/comments/comments-dialog.ts
common/components/comments/comments-items-name-map.ts
common/components/comments/comments-mixin.ts
common/components/comments/comments.helpers.ts

[ch28848] Change tab on comments group click in comments panel, fix elements border in comments mode

---

intervention-workplan-editor/editor-utils/activity-item-mixin.ts

[ch29579] Make activity items commentable (only on Editor page)

[ch29579] Make activity items commentable (only on Editor page)

---

common/components/comments/comments-mixin.ts

[ch29555] [Editor]: Comment Mode - Refresh removes the comment green border from the Results structure

[ch29555] [Editor]: Comment Mode - Refresh removes the comment green border from the Results structure

---

intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch29447]Do not truncate code column

---

common/components/activity/activity-items-table.styles.ts

[ch29501] Removed the dark focus on textarea

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts

[ch29552]Fix CP Output assignment

---

utils/utils.ts

[ch29607]EEPM - fix save 0

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch29590]Fixed table layout (fix layout when no activity items present)

---

common/layout/page-content-header/intervention-page-content-header.ts
intervention-workplan-editor/editor-table.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicator.ts
intervention-workplan/results-structure/pd-indicators.ts

[ch29628] [Results Structure] Standard view overlaps

---

intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch29650] Prevent 'Use input-level' toggle activating on click outside its boundaries

---

intervention-metadata/unicef-details/pdUnicefDetails.models.ts
intervention-metadata/unicef-details/unicef-details.ts

[ch29612] Remove clusters from unicef details display

[ch29612] Remove clusters from unicef details display

---

common/components/activity/activity-item-row.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts

[ch27600] 2 decimals for N. of Units

---

intervention-attachments/attachments-list/intervention-attachment-dialog.ts

[ch29639] Attachments: Validation error not going away

[ch29639] Attachments: Validation error not going away

---

intervention-workplan/hq-contribution/hq-contribution.ts

[ch29634]Fix hq contrib corner case

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicators.ts
intervention-workplan/results-structure/results-structure.ts
intervention-workplan/results-structure/styles/ativities-and-indicators.styles.ts
intervention-workplan/results-structure/styles/results-structure.styles.ts

[ch29613] New Results Structure UI tweaks

---

intervention-review/intervention-review.ts

[ch29688] Change link styles

---

intervention-metadata/other/other.ts

[ch29676]Activation Protocol field tweak

---

intervention-workplan-editor/editor-utils/activities-mixin.ts

[ch29072]Fix lingering validations after edit/cancel/edit again

---

common/layout/page-content-header/intervention-page-content-header.ts

[ch29653] Fix sticky header

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts

[ch29698]Allow add activity for unassociated PD Outputs & [ch29716]Auto validate fix

---

intervention-strategy/geographical-coverage/geographical-coverage.ts

[ch29657] Geographical Coverage: required star misplaced

[ch29657] Geographical Coverage: required star misplaced

---

intervention-workplan-editor/editor-table.ts
intervention-workplan/results-structure/results-structure.ts

[ch29628] Fix z-indexes in result-structure

---

intervention-workplan/results-structure/modals/cp-output-dialog.ts

[ch29693] Add CP Output: Required field validation missing

[ch29693] Add CP Output: Required field validation missing

---

intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch29779] Fix cancel icon width

---

intervention-metadata/other/other.ts

[ch29710] Confidential toggle tweaks

[ch29710] Confidential toggle tweaks

---

common/components/comments/comments-mixin.ts

[29555] [Editor]: Comment Mode - Refresh removes the comment green border from the Results structure

[29555] [Editor]: Comment Mode - Refresh removes the comment green border from the Results structure

---

intervention-workplan/results-structure/modals/cp-output-dialog.ts

[ch29818] Fix select/deselect of Ram Indicators in CP dialog

---

intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch29812]Fix comment mode editor broken UI

---

intervention-workplan-editor/editor-table.ts

[ch29759] Fix menu open on editor page

---

intervention-workplan-editor/editor-table.ts

[ch29819] Comment mode toggle not responding

[ch29819] Comment mode toggle not responding

---

intervention-timing/programmatic-visits/programmatic-visits.ts

[ch29866] Programmatic Visits: Delete button is missing

[ch29866] Programmatic Visits: Delete button is missing

---

intervention-workplan-editor/editor-table.ts

[ch29753]Avoid autovalidate console errors

---

intervention-workplan/results-structure/results-structure.ts

[ch29628] Fix z-index for cp outputs

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts

[ch29731]One entity editable at one time

---

intervention-timing/programmatic-visits/programmatic-visits.ts
utils/intervention-endpoints.ts

[ch29938] Delete programmatic visits is not working after saving the year details

[ch29938] Delete programmatic visits is not working after saving the year details

---

intervention-workplan/results-structure/display-controls.ts

[ch29925] Add focus to result structure header buttons

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts

[ch29861]Save using Ctrl+S

---

intervention-workplan/budget-summary/budgetSummary.models.ts
intervention-workplan/supply-agreement/supply-agreement.ts

[ch29943]total_supply

---

assets/i18n/ar.json
assets/i18n/en.json
intervention-timing/intervention-dates/intervention-dates.ts
intervention-timing/programmatic-visits/programmatic-visits.ts

[ch29864] PD Dates: Updates can also affect Programmatic Visits

[ch29864] PD Dates: Updates can also affect Programmatic Visits

---

common/components/comments/comments-dialog.ts

[ch29956] Fix dialog height update

---

intervention-timing/intervention-dates/intervention-dates.ts

[ch30032]Fix fr warnings not displayed on PD start/end dates after page refresh

---

common/layout/export-intervention-data.ts
common/layout/page-content-header/intervention-page-content-header.ts
common/layout/page-content-header/intervention-page-content-subheader.ts
intervention-actions/intervention-actions.styles.ts
intervention-tabs.ts

[ch30061] Amendment mode: Floating header space
+ Adjust responsive

[ch30061] Amendment mode: Floating header space & print style tweaks

---

intervention-workplan/results-structure/modals/activity-dialog/activity-timeframes.ts

[ch30104] Style issues

---

intervention-workplan/non-financial-contribution/non-financial-contribution.ts

[ch30050] Misplaced tooltip

---

intervention-timing/programmatic-visits/programmatic-visits.ts

[ch30008]Replace substr

---

common/layout/export-intervention-data.ts

[ch30304] Export dropdown options can not be reached with keyboard navigation

[ch30304] Export dropdown options can not be reached with keyboard navigation

---

intervention-strategy/geographical-coverage/sites-widget/map-mixin.ts

[ch30310] Sites: closing Site on map results in no PD details

[ch30310] Sites: closing Site on map results in no PD details

---

common/actions/interventions.ts

[ch30215]List reload criteria update

---

intervention-progress/intervention-reports.ts

[ch30354]Pd Reports - Remove redundant PD ref column

---

common/actions/interventions.ts
intervention-progress/intervention-results-reported.ts

[ch30351][ch30344]Results Reported: indicator font-size, fix missing space

---

intervention-metadata/fund-reservations/fund-reservations.ts
intervention-metadata/intervention-metadata.ts
intervention-metadata/unicef-details/unicef-details.ts
intervention-workplan/results-structure/pd-indicators.ts
intervention-workplan/results-structure/results-structure.ts

[ch29659]Fix navigation errors after current item reset

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-workplan/effective-efficient-programme-mgmt/activity-dialog.ts

[ch30366]Fix effective & efficient programme mgmt validations

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts
intervention-workplan-editor/editor-utils/programme-management-item-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts
intervention-workplan-editor/editor-utils/types.ts

[ch29909] [Editor] Include Effective and Efficient management budget

[ch29909] [Editor] Include Effective and Efficient management budget

---

intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts

[ch30423][Editor]Improve Tab navigation on readonly fields

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts

[ch30364] Update dialog label in View mode

[ch30364] Update dialog label in View mode

---

intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-item-mixin.ts

[ch30448] [Editor]: cannot delete activity item

[ch30448] [Editor]: cannot delete activity item

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts

[ch30450]Fix click in Other Notes after prev. navigating with TAB

---

intervention-workplan-editor/editor-utils/programme-management-mixin.ts
intervention-workplan-editor/editor-utils/types.ts

[ch30442] [Editor]: EEPM - When saving an item the Total is updated to 0

[ch30442] [Editor]: EEPM - When saving an item the Total is updated to 0

---

intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts

[ch30416] Refactor how min date is set for datepicker in edit-hru-dialog.ts file

[ch30416] Refactor how min date is set for datepicker in edit-hru-dialog.ts file

---

intervention-workplan-editor/editor-utils/editor-table-styles.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts

[ch30433] [Editor] Partner Cash label to be aligned to the right for EE Prgm Mgmt activity

[ch30433] [Editor] Partner Cash label to be aligned to the right for EE Prgm Mgmt activity

---

intervention-timing/timing-overview/timing-overview.ts
intervention-timing/timing-overview/timingOverview.models.ts

[ch30319] Use signed_by_unicef_date field to display Date Last Amended

---

intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts

[ch30476] [Editor]: Add new item tooltip present, but the button is not available

[ch30476] [Editor]: Add new item tooltip present, but the button is not available

---

intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts

[ch30435] [Editor] Can't save new activity items when Activity was created when Start/End PD dates were not set

[ch30435] [Editor] Can't save new activity items when Activity was created when Start/End PD dates were not set

---

intervention-progress/intervention-results-reported.ts
intervention-workplan/results-structure/pd-indicator.ts
utils/utils.ts

[ch30517] Icon used for Ratio Indicators is the one for Percentage Indicators [PD/SSFA > Reports / Reports]

[ch30517] Icon used for Ratio Indicators is the one for Percentage Indicators [PD/SSFA > Reports / Reports]

---

assets/i18n/ar.json
assets/i18n/en.json
intervention-metadata/other/other.ts

[ch30567]Fix Partner Cannot update Confidential toggle state

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-item-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts

[ch30520] [Editor]: Effective and Efficient activity items index not fully displayed

[ch30520] [Editor]: Effective and Efficient activity items index not fully displayed

---

intervention-workplan-editor/time-intervals/time-intervals-dialog.ts
intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-workplan/results-structure/modals/activity-dialog/activity-timeframes.ts

[ch30220] Try to fix tab focusing

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts

[ch30480]Add new activity with 1 Tab

---

intervention-strategy/risks/risks.ts
intervention-timing/reporting-requirements/hr/humanitarian-reporting-req-unicef.ts
intervention-timing/reporting-requirements/qpr/quarterly-reporting-requirements.ts
intervention-timing/reporting-requirements/srr/special-reporting-requirements.ts
intervention-workplan/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-workplan/supply-agreement/supply-agreement.ts

[ch30669]Fix reopen dialog after cancelling edit

---

intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts

[ch30657]Dont allow multi edit with Enter & fix focus

---

intervention-timing/reporting-requirements/qpr/qpr-list.ts
intervention-timing/reporting-requirements/srr/special-reporting-requirements.ts

[ch30543] Partner Reporting Requirements: Add pagination for QPRs and Special Reports also

[ch30543] Partner Reporting Requirements: Add pagination for QPRs and Special Reports also

---

intervention-metadata/details-overview/details-overview.ts
intervention-timing/timing-overview/timing-overview.ts
intervention-workplan/budget-summary/budget-summary.ts
intervention-workplan/hq-contribution/hq-contribution.ts
utils/intervention-endpoints.ts
utils/utils.ts

[ch30704]Fix tooltips for rtl layout

---

intervention-tabs.ts

[ch30841] Results Structure overlaps 'In Amendment' frame

[ch30841] Results Structure overlaps 'In Amendment' frame (z-index)

---

intervention-workplan/results-structure/pd-indicator.ts
intervention-workplan/results-structure/styles/ativities-and-indicators.styles.ts

[ch30629]Show scroll when many locations

---

utils/intervention-labels-map.ts

[ch30846]Tweak label for budget owner on Amendment Differences

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-workplan/results-structure/pd-indicator.ts

[ch30857]Fix tooltip for HF indicator

---

intervention-metadata/amendments/pd-amendments.ts

[ch30524]Descending by id order for Amendments

---

intervention-metadata/other/other.selectors.ts
intervention-metadata/other/other.ts

[ch30664]Connect confidential to permissions.view

---

intervention-workplan/results-structure/pd-indicators.ts

[ch31034]Locations names to be bold

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/ro.json
intervention-actions/intervention-actions.constants.ts

[ch29006]Accept as Final

---

intervention-workplan/results-structure/modals/indicator-dialog/mixins/save-indicator-mixin.ts

[ch30858]Ensure target,baseline are numbers

---

intervention-metadata/fund-reservations/fund-reservations.ts

[ch31181]Ensure FR error msg display

---

intervention-workplan/results-structure/pd-indicators.ts

[ch31180] Results Structure - spacing inconsistency

[ch31180] Results Structure - spacing inconsistency

---

common/mixins/results-structure-common.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/results-structure.ts

[ch31182]Fix deactivate,edit activity, inactive prefix, connect to toogle

---

common/types/store.types.ts
intervention-tabs.ts

[ch31228] Investigate why translations don't work without page refresh on language change

[ch31228] Investigate why translations don't work without page refresh on language change

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/pt.json
assets/i18n/ro.json
assets/i18n/ru.json
intervention-tabs.ts
unresolved-other-info.ts

[ch31411]Import ecn fixes

---

intervention-progress/intervention-reports.ts

[ch31509] Progress Reports: Pagination issues

[ch31509] Progress Reports: Pagination issues

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ro.json
assets/i18n/ru.json
utils/intervention-labels-map.ts

[ch31593] Amendment merge: correct label

[ch31593] Amendment merge: correct label

---

intervention-tabs.ts

[ch31511] Progress tab: Results Reported and Reports options often not displayed

[ch31511] Progress tab: Results Reported and Reports options often not displayed

---

intervention-actions/intervention-actions.ts

Fix import

---

intervention-actions/intervention-actions.ts

[ch31710] Cannot Accept as Final/On behalf of Partner

[ch31710] Cannot Accept as Final/On behalf of Partner

---

intervention-workplan-editor/editor-table.ts

[ch31415] Activities editor display -epd

[ch31415] Activities editor display -epd

---

intervention-actions/intervention-actions.constants.ts
intervention-actions/intervention-actions.ts

[ch31416] various ePD export options

[ch31416] various ePD export options

---

common/mixins/results-structure-common.ts
intervention-workplan/results-structure/cp-output-level.ts
intervention-workplan/results-structure/results-structure.ts

[ch31182]]Update `Delete CP Output` permissions

---

intervention-tabs.ts
unresolved-other-info.ts

[ch31801]Fix mark as resolved

---

intervention-workplan-editor/editor-utils/editor-hover-styles.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts

[ch31770][Editor]Activity Items bg color

---

intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts
intervention-workplan-editor/editor-utils/programme-management-item-mixin.ts

[ch31756][Editor]Activity Items Indentation

---

intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicators.ts
intervention-workplan/results-structure/results-structure.ts
intervention-workplan/results-structure/styles/ativities-and-indicators.styles.ts

[ch31799]Results Structure Indentations & table header bg and border

---

intervention-workplan/results-structure/pd-indicator.ts
intervention-workplan/results-structure/styles/ativities-and-indicators.styles.ts

[ch31764]Results structure - indent show loc. link

---

common/mixins/activities-common.mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts

[ch31858]Editor- Fix validation not triggered

---

intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts
intervention-workplan-editor/editor-utils/programme-management-item-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts

[ch31805]Editor-Emphasize edit-mode for Activity&Items

---

intervention-workplan-editor/editor-table.ts

[ch31495] Editor-fix can focus empty area

---

intervention-workplan/results-structure/pd-activities.ts

[ch31793]Fix pd actions dropdown moves with scroll

---

intervention-workplan-editor/editor-utils/programme-management-item-mixin.ts

[ch31858]Fix cash validation

---

intervention-workplan/results-structure/pd-indicator.ts

[ch31793]Fix pd indic. actions moves with scroll

---

intervention-workplan-editor/editor-table.ts

[ch31886] [Editor] Add a Label for the 'Add PD Output empty row with add btn'

[ch31886] [Editor] Add a Label for the 'Add PD Output empty row with add btn'

---

intervention-strategy/geographical-coverage/sites-widget/map-mixin.ts
intervention-strategy/geographical-coverage/sites-widget/sites-widget.ts

[ch32020] Replace leaflet basemap

[ch32020] Replace leaflet basemap

---

intervention-workplan/results-structure/cp-output-level.ts
intervention-workplan/results-structure/results-structure.ts

[ch31917]Fix delete CP Output

---

intervention-progress/intervention-reports.ts
intervention-tabs.ts
intervention-workplan-editor/editor-table.ts

[ch31232]Fix pd report routing

---

intervention-strategy/geographical-coverage/sites-dialog.ts

[ch32106] Selected Sites: unnecessary and non functional scroll showing up

[ch32106] Selected Sites: unnecessary and non functional scroll showing up

---

intervention-actions/intervention-actions.ts

[ch32247] PD status is not updated in the list

[ch32247] PD status is not updated in the list

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ro.json
assets/i18n/ru.json

[ch31413] ePD -Headquarter contribution

[ch31413] ePD -Headquarter contribution

---

intervention-tabs.ts

[ch32170] PD details: When switching the language, the progress tab becomes disabled

[ch32170] PD details: When switching the language, the progress tab becomes disabled

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts

[ch32241]Disable arrow nav in comment mode

---

intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-item-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts

[ch32241][Editor]Disable arrow nav in comment mode

---

intervention-strategy/geographical-coverage/sites-widget/map-mixin.ts

[ch32310] Arcgis map fallback show old map

[ch32310] Arcgis map fallback show old map

---

common/components/prp-country-data/prp-country-data.ts

[ch32240]Disable PRP requests on ePD

---

intervention-attachments/prc-document/prc-document.ts
intervention-metadata/other/other.ts
intervention-metadata/review-and-sign/review-and-sign.ts
intervention-metadata/unicef-details/unicef-details.ts
intervention-strategy/document-details/document-details.ts
intervention-strategy/gender-equity-rating/gender-equity-rating.ts
intervention-strategy/geographical-coverage/geographical-coverage.ts
intervention-timing/intervention-dates/intervention-dates.ts
intervention-timing/programmatic-visits/programmatic-visits.ts
intervention-workplan/hq-contribution/hq-contribution.ts
intervention-workplan/non-financial-contribution/non-financial-contribution.ts

[ch32373]Console errors fixes

---

intervention-metadata/unicef-details/unicef-details.ts
intervention-strategy/geographical-coverage/geographical-coverage.ts

[ch32355]Keep unsaved changes on nav between tabs

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ro.json
assets/i18n/ru.json
intervention-actions/intervention-actions.constants.ts
intervention-review/overall-approval/overall-approval.ts
intervention-review/reviews-list/reviews-list.ts

[ch32418]PRC Review - add missing translations

---

intervention-actions/intervention-actions.ts

[ch32199] Continuous Loading at Amendment Merge

[ch32199] Continuous Loading at Amendment Merge

---

intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-item-mixin.ts

[ch32442]Up  Arrow navigation thrown off after adding a new activity item

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ro.json
assets/i18n/ru.json
common/components/intervention/pd-termination.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts

[ch32431]Missing translations - pd termination, activity item delete

---

intervention-strategy/document-details/document-details.ts

[ch31978] Adjustment to ePD to include adjustments from the procedure - Checkbox styles

[ch31978] Adjustment to ePD to include adjustments from the procedure - Checkbox styles

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ro.json
assets/i18n/ru.json

[ch26701] Update translations for new keys

[ch31978] Update translations for new keys 

---

common/components/comments/comments-mixin.ts
intervention-tabs.ts
intervention-workplan-editor/editor-table.ts

[ch32460] Fix duplicate comments dialog

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ro.json
assets/i18n/ru.json
intervention-progress/intervention-reports.ts
intervention-progress/reports/final-progress-report.ts
intervention-tabs.ts

[ch32086]Final Progress Report And Review was approved checkbox

---

intervention-metadata/partner-details/partner-info.ts

[ch32492] [Intermittent] Double or triple API request to staff_members

[ch32492] [Intermittent] Double or triple API request to staff_members

---

intervention-strategy/geographical-coverage/geographical-coverage.ts

[ch32496]Fix See Hierarchy link

---

intervention-progress/reports/final-progress-report.ts

[ch32086]Fix final progress report

---

intervention-progress/reports/final-progress-report.ts

[ch32086]Fix cancel & btn for final-progress-report

---

intervention-metadata/partner-details/partner-info.ts
intervention-metadata/unicef-details/unicef-details.ts

[ch32544][Intermittent] Saved UNICEF Details not displayed after page refresh

---

intervention-metadata/fund-reservations/fund-reservations.ts
intervention-progress/layout/etools-ram-indicators.ts
intervention-timing/intervention-dates/intervention-dates.ts
intervention-timing/programmatic-visits/programmatic-visits.ts
intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
intervention-timing/reporting-requirements/hr/humanitarian-reporting-req-unicef.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
intervention-timing/reporting-requirements/qpr/quarterly-reporting-requirements.ts

[ch32526]All toasts to have ok btn

---

intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts

[ch32716] Uncaught TypeError: Cannot read properties of undefined (reading '0')

[ch32716] Uncaught TypeError: Cannot read properties of undefined (reading '0')

---

intervention-metadata/amendments/add-amendment-dialog.ts
utils/utils.ts

[ch32710] Amendment types: Validation not going away

[ch32710] Amendment types: Validation not going away

---

intervention-strategy/geographical-coverage/sites-widget/location-widget.styles.ts
intervention-strategy/geographical-coverage/sites-widget/sites-widget.ts

[ch32762] Tab navigation not working properly

[ch32762] Tab navigation not working properly

---

common/components/comments/comments-mixin.ts

[ch32787] Comment Mode: You can edit and save changes on the PD when navigating with tab

[ch32787] Comment Mode: You can edit and save changes on the PD when navigating with tab

---

intervention-attachments/intervention-attachments.ts

[ch32805] PRC attachments (legacy) should not bee seen by the partner

[ch32805] PRC attachments (legacy) should not bee seen by the partner

---

common/budget-summary/budget-summary.ts
common/components/comments-panels/comments-list/comments-panel-header.ts
common/components/comments-panels/comments-panels.ts
common/components/comments-panels/common-comments.styles.ts
common/components/comments/comments-items-name-map.ts
common/components/comments/comments-mixin.ts
common/components/intervention/review-checklist-popup.ts
intervention-attachments/intervention-attachments.ts
intervention-metadata/amendments/pd-amendments.ts
intervention-metadata/financial/financial-component.ts
intervention-metadata/other/other.ts
intervention-strategy/risks/risks.ts
intervention-tabs.ts
intervention-timing/timing-overview/timing-overview.ts
unresolved-other-info.ts

Fix lint issues

---

common/components/comments-panels/comments-list/comments-group.ts
common/components/comments-panels/comments-list/comments-list.ts
common/components/comments-panels/comments-list/comments-panel-header.ts
common/components/comments-panels/comments-panels.ts
common/components/comments-panels/common-comments.styles.ts
common/components/comments-panels/messages-panel/message-item.ts
common/components/comments-panels/messages-panel/messages-panel-header.ts
common/components/comments-panels/messages-panel/messages-panel.ts
common/components/comments/comment.styles.ts
common/components/comments/comments-dialog.ts
common/components/comments/comments-mixin.ts
common/components/comments/comments.helpers.ts
intervention-tabs.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts

[ch28848] Create new comments panel - comments fixes
[ch32891] Comments mode: navigation issues
[ch32888] Comment Panel Improvements
[ch32890] Comment Panel Improvements (compatibility)
[ch32891] Comments mode: navigation issues
[ch32787] Comment Mode: You can edit and save changes on the PD when navigating with tab - focus border comment

[ch28848] Create new comments panel - comments fixes

---

common/components/comments-panels/comments-list/comments-list.ts
common/components/comments-panels/comments-list/comments-panel-header.ts
common/components/comments-panels/common-comments.styles.ts
common/components/comments-panels/messages-panel/messages-panel-header.ts
common/components/comments/comments.helpers.ts

[ch28848] Create new comments panel - Fixes part 2

[ch28848] Create new comments panel - Fixes part 2

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
common/components/comments/comments-items-name-map.ts
intervention-workplan/hq-contribution/hq-contribution.ts

[ch32849] Frontend: Change hq-contribution to capacity-strengthening-costs

[ch32849] Frontend: Change hq-contribution to capacity-strengthening-costs

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
intervention-strategy/document-details/document-details.ts
intervention-strategy/document-details/documentDetails.models.ts
utils/intervention-labels-map.ts

[ch32923] Strategy tab: Add `Other` field in the Document Details section

[ch32923] Strategy tab: Add `Other` field in the Document Details section

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
common/components/comments-panels/comments-list/comments-list.ts
common/components/comments-panels/messages-panel/message-item.ts
common/components/comments-panels/messages-panel/messages-panel-header.ts
common/components/comments/comment.ts

[ch32888] Comment Panel Improvements - Navigation improvements

[ch32888] Comment Panel Improvements - Navigation improvements

---

intervention-tabs.ts

[ch33014] Translations: Values not updated at language switch

[ch33014] Translations: Values not updated at language switch

---

common/types/store.types.ts
intervention-metadata/unicef-details/unicef-details.ts

[ch33064] Translations: Values not updated at language switch part II

[ch33064] Translations: Values not updated at language switch part II

---

common/components/comments-panels/comments-list/comments-group.ts
common/components/comments-panels/comments-list/comments-list.ts
common/components/comments-panels/comments-panels.ts
common/components/comments-panels/messages-panel/messages-panel-header.ts
common/components/comments-panels/messages-panel/messages-panel.ts
common/components/comments/comments-items-name-map.ts
common/components/comments/comments-types.ts
common/components/comments/comments.helpers.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts

[ch32997] Comments panel: Bring data from reference items

[ch32997] Comments panel: Bring data from reference items

---

intervention-actions/intervention-actions.styles.ts

[ch33131]When Arabic language is set, the split button doesn't look ok

---

intervention-actions/intervention-actions.styles.ts

[ch33140]Fix 3 vertical dots icon for RTL layout

---

common/components/comments-panels/comments-list/comments-panel-header.ts
common/components/comments-panels/common-comments.styles.ts
common/components/comments-panels/messages-panel/message-item.ts
common/components/comments-panels/messages-panel/messages-panel-header.ts
common/components/comments-panels/messages-panel/messages-panel.ts
common/components/comments/comment.styles.ts

[ch32780] Tab navigation: Unwanted black border on focus

[ch32780] Tab navigation: Unwanted black border on focus

---

intervention-workplan/results-structure/modals/indicator-dialog/non-cluster-indicator.ts

[ch33146] Misplaced radio buttons for Indicator types

[ch33146] Misplaced radio buttons for Indicator types

---

intervention-strategy/geographical-coverage/sites-widget/sites-widget.ts

[ch32796] Leaflet: [Intermittent] Current country map not loaded

[ch32796] Leaflet: [Intermittent] Current country map not loaded

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
intervention-timing/intervention-dates/intervention-dates.ts
utils/intervention-labels-map.ts

[ch33170]Contingency PD: Activation letter attachment validation error

---

intervention-timing/activity-timeframes/activity-timeframes.styles.ts
intervention-timing/activity-timeframes/activity-timeframes.ts
intervention-timing/reporting-requirements/qpr/qpr-list.ts
intervention-timing/timing-overview/timing-overview.ts

[ch33156]Fix Date translation not applied on lang change (Timing tab)

---

assets/i18n/fr.json
intervention-actions/intervention-actions.constants.ts

[ch33233]French: Missing Translations FE

---

common/actions/common-actions.ts
common/types/store.types.ts
intervention-workplan-editor/editor-table.ts

[ch33266]Remove sidemenu state from redux

---

assets/i18n/fr.json

[ch33287]Fix duplicate translation

---

intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch33299] Activity Data dialog: Scroll in Other Notes view mode not working

[ch33299] Activity Data dialog: Scroll in Other Notes view mode not working

---

common/components/activity/activity-items-table.ts
common/mixins/activities-common.mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan/effective-efficient-programme-mgmt/activity-dialog.ts

[ch33325]Fix Activity item validation

---

intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch33340] Results Structure/Activity-Item row is not automatically added

[ch33340] Results Structure/Activity-Item row is not automatically added

---

intervention-metadata/partner-details/partner-info.ts

[ch33426] Console error on intervention/ metadata tab

[ch33426] Console error on intervention/ metadata tab

---

intervention-metadata/amendments/pd-amendments.ts
intervention-review/reviews-list/reviews-list.ts

[ch33478] Misalignements - agreement details, review tab, amendments

[ch33478] Misalignements - agreement details, review tab, amendments

---

intervention-metadata/amendments/add-amendment-dialog.ts

[ch33462]Fix console err on select Amendment Type

---

intervention-timing/reporting-requirements/srr/special-reporting-requirements.ts

[ch33464]Refactor confirm dialog for delete special report

---

common/layout/export-intervention-data.ts
intervention-actions/intervention-actions.ts
intervention-strategy/geographical-coverage/geographical-coverage.ts
intervention-workplan/results-structure/display-controls.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicator.ts
intervention-workplan/results-structure/styles/ativities-and-indicators.styles.ts

[ch33131] [ch33272] [ch33140] Fixes

[ch33131] [ch33272] [ch33140] Fixes

---

intervention-actions/intervention-actions.ts
intervention-metadata/amendments/pd-amendments.ts

[ch33474] After amendment merge, the [Amended] PD remains in the PD list and gives a 404/not found when it's accessed

[ch33474] After amendment merge, the [Amended] PD remains in the PD list and gives a 404/not found when it's accessed

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
intervention-metadata/fund-reservations/fund-reservations.ts

[ch33429] Fr warnings not translated on PD list

[ch33429] Fr warnings not translated on PD list

---

intervention-timing/programmatic-visits/programmatic-visits.ts
intervention-timing/programmatic-visits/pv-quarter.ts

[ch33295]Fix delete when slow network, select site visibility, scroll down after add

---

common/components/comments-panels/messages-panel/messages-panel.ts

[ch33274]Localize Post in messages-panel

---

intervention-workplan/results-structure/results-structure.ts

[ch33569] PD Output label missing padding

[ch33569] PD Output label missing padding

---

intervention-workplan/results-structure/pd-activities.ts

[ch33677] Results structure Standard view: Inactive tag for activities missing translations

[ch33677] Results structure Standard view: Inactive tag for activities missing translations

---

intervention-strategy/geographical-coverage/grouped-locations-dialog.ts

[ch33638] Geographical Coverage: The Partner does not see the group location options

[ch33638] Geographical Coverage: The Partner does not see the group location options

---

common/actions/interventions.ts
common/mixins/results-structure-common.ts
intervention-attachments/attachments-list/attachments-list.ts
intervention-strategy/risks/risks.ts
intervention-workplan-editor/editor-table.ts
intervention-workplan/results-structure/pd-indicators.ts

[ch33587] Deleting items when the network is slow

[ch33587] Deleting items when the network is slow

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts

[ch33489]Fix editor exits edit mode

---

common/actions/interventions.ts
intervention-workplan/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts

[ch33414] PD EEPM - add comments discrepancy

[ch33414] PD EEPM - add comments discrepancy

---

intervention-metadata/review-and-sign/review-and-sign.ts

[ch33886] Metadata tab/ Signatures&Dates - Cut off label

[ch33886] Metadata tab/ Signatures&Dates - Cut off label

---

assets/i18n/pt.json

[ch33926]Portuguese tweaks -dev

---

intervention-workplan/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts

[ch33914]EEPM Edit activity issues

---

assets/i18n/ar.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/ru.json

[ch33972]Fix FACE translation

---

assets/i18n/fr.json

[ch34026] French: Missing closing bracket

[ch34026] French: Missing closing bracket

---

intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts

[ch34640]Spacing/alignement fixes

---

intervention-strategy/geographical-coverage/geographical-coverage.ts

[ch34635]Shoelace input - Geographical Coverage/ Locations label blur

---

intervention-strategy/geographical-coverage/geographical-coverage.ts
intervention-strategy/risks/risk-dialog.ts

[ch34643]Shoelace - validation msg doesnt show up sometimes

---

common/components/sites-widget/sites-dialog.ts
intervention-metadata/other/other.ts
intervention-workplan-editor/editor-table.ts
intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch34661]Sl textarea - handle max-height

---

common/components/sites-widget/sites-dialog.ts
intervention-metadata/other/other.ts
intervention-workplan-editor/editor-table.ts
intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch34671]Activation protocol not displayed

---

intervention-attachments/prc-document/prc-document.ts
intervention-metadata/financial/financial-component.ts
intervention-metadata/other/other.ts
intervention-metadata/partner-details/partner-info.ts
intervention-metadata/unicef-details/unicef-details.ts
intervention-progress/layout/etools-ram-indicators.ts
intervention-progress/monitoring-visits-list.ts
intervention-strategy/document-details/document-details.ts
intervention-strategy/gender-equity-rating/gender-equity-rating.ts
intervention-workplan/hq-contribution/hq-contribution.ts
intervention-workplan/non-financial-contribution/non-financial-contribution.ts
intervention-workplan/supply-agreement/supply-agreement.ts

Adding etools-loading and etools-profile-dropdown

Adding etools-loading and etools-profile-dropdown

---

intervention-attachments/prc-document/prc-document.ts
intervention-metadata/amendments/pd-amendments.ts
intervention-metadata/details-overview/details-overview.ts
intervention-metadata/financial/financial-component.ts
intervention-metadata/fund-reservations/fund-reservations.ts
intervention-metadata/other/other.ts
intervention-metadata/partner-details/partner-info.ts
intervention-metadata/review-and-sign/review-and-sign.ts
intervention-metadata/unicef-details/unicef-details.ts
intervention-progress/intervention-implementation-status.ts
intervention-progress/intervention-monitoring-activities.ts
intervention-progress/intervention-reports.ts
intervention-progress/intervention-results-reported.ts
intervention-progress/intervention-summary.ts
intervention-progress/layout/etools-ram-indicators.ts
intervention-progress/monitoring-visits-list.ts
intervention-progress/reports/final-progress-report.ts
intervention-review/general-review-information/general-review-information.ts
intervention-review/review-members/review-members.ts
intervention-strategy/document-details/document-details.ts
intervention-strategy/gender-equity-rating/gender-equity-rating.ts
intervention-strategy/risks/risks.ts
intervention-timing/activity-timeframes/activity-timeframes.ts
intervention-timing/intervention-dates/intervention-dates.ts
intervention-timing/reporting-requirements/partner-reporting-requirements.ts
intervention-timing/timing-overview/timing-overview.ts
intervention-workplan/hq-contribution/hq-contribution.ts
intervention-workplan/non-financial-contribution/non-financial-contribution.ts
intervention-workplan/supply-agreement/supply-agreement.ts
unresolved-other-info.ts

Adding etools-content-panel and etools-collapse

Adding etools-content-panel and etools-collapse

---

intervention-progress/intervention-results-reported.ts
intervention-workplan/results-structure/display-controls.ts

[ch34734]Replace form-element-wrapper

---

intervention-progress/intervention-reports.ts
intervention-timing/reporting-requirements/styles/etools-cp-header-actions-bar-styles.ts

[ch34740]Status component style issues

---

common/components/comments-panels/messages-panel/messages-panel.ts
common/components/comments/comments-dialog.ts
common/components/comments/edit-comments-base.ts
intervention-progress/intervention-reports.ts
intervention-timing/reporting-requirements/styles/etools-cp-header-actions-bar-styles.ts

[ch34708]Console error when enabling comment mode

---

common/components/comments-panels/messages-panel/messages-panel.ts
common/components/comments/comments-dialog.ts
common/components/comments/edit-comments-base.ts
common/layout/page-content-header/intervention-page-content-header.ts
intervention-progress/intervention-reports.ts
intervention-progress/intervention-results-reported.ts
intervention-progress/reports/indicator-report-target.ts
intervention-timing/reporting-requirements/styles/etools-cp-header-actions-bar-styles.ts

[ch34761]Remove css mixins

---

intervention-metadata/fund-reservations/fund-reservations.ts

[ch34809]Fix Add/Update FR Numbers modal remain displayed

---

common/components/activity/activity-items-table.styles.ts
intervention-metadata/fund-reservations/fund-reservations.ts
intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts

[ch34796]Fix Required star styles

---

intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts

Fix etools-dialog closing

---

intervention-workplan-editor/time-intervals/time-intervals.ts

[ch34733]Fix time intervals tooltips

---

intervention-attachments/attachments-list/attachments-list.ts
intervention-metadata/other/other.ts
intervention-tabs.ts
intervention-timing/reporting-requirements/styles/etools-cp-header-actions-bar-styles.ts
intervention-workplan-editor/time-intervals/time-intervals-dialog.ts
intervention-workplan-editor/time-intervals/time-intervals.ts
intervention-workplan/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-workplan/results-structure/display-controls.ts
intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/non-cluster-indicator.ts
intervention-workplan/results-structure/results-structure.ts

[ch34812]Replace paper-toggle with sl-swith

---

common/components/activity/activity-item-row.ts
common/components/activity/activity-items-table.styles.ts
intervention-attachments/attachments-list/attachments-list.ts
intervention-metadata/other/other.ts
intervention-tabs.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
intervention-timing/reporting-requirements/styles/etools-cp-header-actions-bar-styles.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts
intervention-workplan-editor/time-intervals/time-intervals-dialog.ts
intervention-workplan-editor/time-intervals/time-intervals.ts
intervention-workplan/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-workplan/results-structure/display-controls.ts
intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/non-cluster-indicator.ts
intervention-workplan/results-structure/results-structure.ts

[ch34901]Activity items style issues, Align currency amt to right, Fix valid msg shifting UI

---

common/components/activity/activity-item-row.ts
common/components/activity/activity-items-table.styles.ts
intervention-attachments/attachments-list/attachments-list.ts
intervention-metadata/other/other.ts
intervention-tabs.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
intervention-timing/reporting-requirements/styles/etools-cp-header-actions-bar-styles.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/arrows-navigation-mixin.ts
intervention-workplan-editor/editor-utils/editor-table-styles.ts
intervention-workplan-editor/time-intervals/time-intervals-dialog.ts
intervention-workplan-editor/time-intervals/time-intervals.ts
intervention-workplan/effective-efficient-programme-mgmt/activity-dialog.ts
intervention-workplan/results-structure/display-controls.ts
intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/non-cluster-indicator.ts
intervention-workplan/results-structure/results-structure.ts

[ch34940]Fix editor/currency field cant be reached with tab

---

intervention-tabs.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts

[ch34913] On language change tab bottom border not adjusting according to text

[ch34913] On language change tab bottom border not adjusting according to text

---

intervention-actions/accept-for-partner.ts
intervention-workplan/results-structure/modals/indicator-dialog/mixins/save-indicator-mixin.ts

[ch34959][ch34926Fix console err on save indicator& date field length

---

intervention-tabs.ts
intervention-timing/programmatic-visits/programmatic-visits.ts

[ch34923]Fix 2 Tabs partially selected when clicking items in Comments Panel

---

intervention-workplan/results-structure/modals/indicator-dialog/non-cluster-indicator.ts

[ch35006]"Add Indicator Percent/Ratio" allignment issues

---

common/layout/export-intervention-data.ts
intervention-actions/intervention-actions.styles.ts
intervention-actions/intervention-actions.ts
intervention-workplan/results-structure/display-controls.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicator.ts
intervention-workplan/results-structure/results-structure.ts
intervention-workplan/results-structure/styles/ativities-and-indicators.styles.ts

[ch34771] Replace paper-listbox with Shoelace correspondent

[ch34771] Replace paper-listbox with Shoelace correspondent

---

intervention-workplan/hq-contribution/hq-contribution.ts

[ch35024]Replace paper-slider with sl-range

---

common/components/intervention/review-checklist-popup.ts
intervention-attachments/attachments-list/intervention-attachment-dialog.ts
intervention-metadata/financial/financial-component.ts
intervention-metadata/review-and-sign/review-and-sign.ts
intervention-progress/reports/final-progress-report.ts
intervention-strategy/document-details/document-details.ts
intervention-workplan/hq-contribution/hq-contribution.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/non-cluster-indicator.ts

[ch35016]Replace paper-checkbox with sl-checkbox

---

common/components/intervention/review-checklist-popup.ts
intervention-metadata/financial/financial-component.ts
intervention-progress/layout/etools-progress-bar.ts
intervention-strategy/gender-equity-rating/gender-equity-rating.ts
intervention-workplan/results-structure/modals/indicator-dialog/non-cluster-indicator.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicators.ts
intervention-workplan/results-structure/results-structure.ts

[ch35059]Use sl-progress-bar

---

intervention-progress/fund-reservations-display.ts
intervention-progress/intervention-results-reported.ts
intervention-progress/intervention-summary.ts
intervention-progress/layout/etools-ram-indicators.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
intervention-timing/reporting-requirements/srr/add-edit-special-rep-req.ts

[ch35097]Replace iron-label

---

common/components/comments-panels/messages-panel/message-item.ts
common/components/comments-panels/messages-panel/messages-panel-header.ts

[ch34647] Comments not translated entirely when changing the language

[ch34647] Comments not translated entirely when changing the language

---

common/components/activity/activity-items-table.ts
intervention-metadata/fund-reservations/update-fr-numbers.ts
intervention-metadata/other/other.ts
intervention-metadata/review-and-sign/review-and-sign.ts
intervention-tabs.ts
intervention-timing/reporting-requirements/partner-reporting-requirements.ts
intervention-workplan/hq-contribution/hq-contribution.ts
intervention-workplan/results-structure/modals/indicator-dialog/cluster-indicator.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts
intervention-workplan/results-structure/modals/indicator-dialog/non-cluster-indicator.ts
intervention-workplan/supply-agreement/supply-agreement.ts
utils/utils.ts

[ch35170] Replace iron-pages

---

common/layout/status/intervention-report-status.ts
intervention-workplan/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicator.ts

Fix icon names

---

common/budget-summary/budget-summary.ts
common/components/comments-panels/comments-list/comments-list.ts
intervention-metadata/fund-reservations/fund-reservations.ts
intervention-progress/fund-reservations-display.ts
intervention-progress/intervention-reports.ts
intervention-progress/intervention-results-reported.ts
intervention-timing/intervention-dates/intervention-dates.ts

Adding etools-app-selector, linting, use latest etools-unicef/etools-modules-common

Adding etools-app-selector, linting, use latest etools-unicef/etools-modules-common

---

intervention-progress/intervention-reports.ts
intervention-timing/reporting-requirements/partner-reporting-requirements.ts

[ch35098] Replace iron-media-query

[ch35098] Replace iron-media-query

---

unresolved-other-info.ts

[ch35301] PMP & ePD shoelace migration issues 3

[ch35301] PMP & ePD shoelace migration issues 3

---

common/components/comments/comments-dialog.ts
common/components/intervention/review-checklist-popup.ts
common/mixins/truncate.mixin.ts
intervention-actions/intervention-actions.styles.ts
intervention-actions/intervention-actions.ts
intervention-metadata/fund-reservations/update-fr-numbers.ts
intervention-metadata/review-and-sign/review-and-sign.ts
intervention-review/review-members/review-members.ts
intervention-strategy/geographical-coverage/geographical-coverage.ts
intervention-timing/programmatic-visits/programmatic-visits.ts
intervention-timing/programmatic-visits/pv-quarter.ts
intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
intervention-timing/reporting-requirements/hr/humanitarian-reporting-req-unicef.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
intervention-timing/reporting-requirements/qpr/quarterly-reporting-requirements.ts
intervention-timing/reporting-requirements/srr/special-reporting-requirements.ts
intervention-workplan-editor/editor-table.ts
intervention-workplan-editor/editor-utils/activities-mixin.ts
intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-item-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-mixin.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dissaggregations.ts
intervention-workplan/results-structure/modals/indicator-dialog/non-cluster-indicator.ts

[ch35333] Clean-up, refactor, fix buttons

[ch35333] Clean-up, refactor, fix buttons

---

intervention-workplan-editor/editor-utils/activity-item-mixin.ts
intervention-workplan-editor/editor-utils/programme-management-item-mixin.ts
intervention-workplan/hq-contribution/hq-contribution.ts

Adapt rollup build for development + optimization (switching to compile with esbuild) + extend etools_input with all properties from sholace input

Adapt rollup build for development + optimization (switching to compile with esbuild) + extend etools_input with all properties from sholace input

---

common/components/activity/activity-item-row.ts
common/mixins/truncate.mixin.ts
intervention-metadata/financial/financial-component.ts
intervention-progress/reports/final-progress-report.ts
intervention-strategy/document-details/document-details.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
intervention-timing/reporting-requirements/srr/add-edit-special-rep-req.ts
intervention-workplan/effective-efficient-programme-mgmt/effective-efficient-programme-mgmt.ts
intervention-workplan/results-structure/pd-activities.ts

[ch35358] Ui fixes

---

intervention-workplan-editor/editor-table.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts

Tabs to upperscase + fix save add indicator

Tabs to upperscase + fix save add indicator

---

common/components/intervention/review-checklist-popup.ts
intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
intervention-timing/reporting-requirements/hr/humanitarian-reporting-req-unicef.ts
intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
intervention-timing/reporting-requirements/qpr/quarterly-reporting-requirements.ts
intervention-timing/reporting-requirements/srr/add-edit-special-rep-req.ts
intervention-timing/reporting-requirements/srr/special-reporting-requirements.ts
intervention-workplan/results-structure/display-controls.ts
intervention-workplan/results-structure/pd-activities.ts
intervention-workplan/results-structure/pd-indicator.ts

[ch35394] PMP & ePD shoelace migration issues 5

[ch35394] PMP & ePD shoelace migration issues 5

---

intervention-timing/programmatic-visits/programmatic-visits.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/mixins/save-indicator-mixin.ts

[ch35394] etools tabs fixes for indicator dialog

[ch35394] etools tabs fixes for indicator dialog

---

intervention-metadata/other/other.ts
intervention-metadata/partner-details/partner-info.ts
intervention-metadata/unicef-details/unicef-details.ts
intervention-strategy/document-details/document-details.ts
intervention-strategy/gender-equity-rating/gender-equity-rating.ts
intervention-strategy/geographical-coverage/geographical-coverage.ts
intervention-workplan/hq-contribution/hq-contribution.ts
intervention-workplan/supply-agreement/supply-agreement-dialog.ts

[ch35394] Fix input focus

---

intervention-tabs.ts

[ch35560] PMP & ePD shoelace migration issues 7

[ch35560] PMP & ePD shoelace migration issues 7

---

intervention-tabs.ts
intervention-timing/programmatic-visits/programmatic-visits.ts

[ch35612] PMP & ePD shoelace migration issues 8

[ch35612] PMP & ePD shoelace migration issues 8

---

intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts

Make inactive Indicators readonly

Make inactive Indicators readonly

---

intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts

[ch35953] Humanitarian Report - 500 Internal Server Error when saving report without a Start Date selected

[ch35953] Humanitarian Report - 500 Internal Server Error when saving report without a Start Date selected

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
intervention-actions/intervention-actions.ts

Adjust loading message for Amendment merge

Adjust loading message for Amendment merge

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
intervention-actions/intervention-actions.ts
intervention-review/review-members/review-members.ts
intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts
utils/utils.ts

Update migration branch with changes made on develop, ch[35953], [ch35959], [ch35846]

Update migration branch with changes made on develop, ch[35953], [ch35959], [ch35846] 

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
intervention-workplan/results-structure/modals/cp-output-dialog.ts
intervention-workplan/results-structure/results-structure.ts

[ch33484] Need for the ability to edit the CP Output for PDs in Development Stage

[ch33484] Need for the ability to edit the CP Output for PDs in Development Stage

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
intervention-workplan/supply-agreement/supply-agreement.ts

[ch30974] Additional text in a supply plan tooltip

[ch30974] Additional text in a supply plan tooltip

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
common/components/comments-panels/messages-panel/message-item.ts
common/components/comments-panels/messages-panel/messages-panel-header.ts
intervention-actions/intervention-actions.ts
intervention-review/review-members/review-members.ts
intervention-strategy/document-details/document-details.ts
intervention-timing/reporting-requirements/hr/edit-hru-dialog.ts
intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts
utils/utils.ts

Reverts unicef/intervention-tab-pages#1087

Revert "Develop"

---

intervention-progress/intervention-monitoring-activities.ts
intervention-progress/monitoring-visits-list.ts
utils/intervention-endpoints.ts

[ch37121 PMP Interventions Monitoring Activities, replace requests to `tpm` and `t2f` with request to 'fm' activities

[ch37121 PMP Interventions Monitoring Activities, populate with 'fm' activities instead of `tpm` and `t2f`

---

intervention-progress/reports/final-progress-report.ts
intervention-tabs.ts

[ch37329]  final_review_approved is not showing up when the user is able to edit.

[ch37329]  final_review_approved is not showing up when the user is able to edit.

---

intervention-attachments/attachments-list/attachments-list.ts

[ch33483] Attachments

---

assets/i18n/ar.json
assets/i18n/en.json
assets/i18n/es.json
assets/i18n/fr.json
assets/i18n/pt.json
assets/i18n/ru.json
common/components/intervention/review-checklist-popup.ts
intervention-review/overall-approval/overall-approval.ts
intervention-review/review-members/review-members.ts

[ch31859]  Add a review level for the Rep

[ch31859]  Add a review level for the Rep
