unicef/intervention-tab-pages

- intervention-results/supply-agreement/supply-agreement-dialog.ts
[ch22270] 'other_mentions' field missing from add/edit supply agreement dialog
> [ch22270] 'other_mentions' field missing from add/edit supply agreement dialog

- utils/intervention-endpoints.ts
[ch22437] Accept: Can not update intervention: the URL doesn't end in a slash
> [ch22437] Accept: Can not update intervention: the URL doesn't end in a slash

- intervention-tabs.ts
[ch22560] Hide Progress and Reports tabs when prp_mode_off is active for selected country
> [ch22560] Hide Progress and Reports tabs when prp_mode_off is active for selected country

- intervention-results/results-structure/pd-activities.ts
[ch22922] Results Structure/Activity row height should be the same as indicator row
> [ch22922] Results Structure/Activity row height should be the same as indicator row

- utils/intervention-endpoints.ts
[ch24144] Residual 'Unassociated to CP Output' after Partner user adds and then deletes a PD output
> [ch24144] Residual 'Unassociated to CP Output' after Partner user adds and then deletes a PD output

- intervention-timing/reporting-requirements/qpr/edit-qpr-dialog.ts
[ch24933] Missing informative row ID when editing Quarterly Partner Reporting Requirement
> [ch24933] Missing informative row ID when editing Quarterly Partner Reporting Requirement

- intervention-results/results-structure/modals/activity-dialog/activity-data-dialog.ts
[ch25151] Activity Data dialog: Total values is cut off if CSO cash and UNICEF cash have high values
> [ch25151] Activity Data dialog: Total values is cut off if CSO cash and UNICEF cash have high values

- assets/i18n/ar.json
- assets/i18n/en.json
- assets/i18n/ro.json
- intervention-attachments/prc-document/prc-document.ts
[ch26396] Add 'For legacy PDs only' to the 'PRC Review Document' label from Attachments tab
> [ch26396] Add 'For legacy PDs only' to the 'PRC Review Document' label from Attachments tab

- intervention-workplan/results-structure/modals/indicator-dialog/indicator-dialog.ts
- intervention-workplan/results-structure/modals/indicator-dialog/non-cluster-indicator.ts
[ch26907] On Indicator modal, the high frequency toggle should not show up for the partner.
> [ch26907] On Indicator modal, the high frequency toggle should not show up for the partner.

- common/components/activity/activity-items-table.ts
- intervention-workplan/effective-efficient-programme-mgmt/activity-dialog.ts
- intervention-workplan/results-structure/modals/activity-dialog/activity-data-dialog.ts
[ch26937] [High] Adding input budget on activity pop-up extends the popup below the browser bottom and makes the save button inaccessible
> [ch26937] [High] Adding input budget on activity pop-up extends the popup below the browser bottom and makes the save button inaccessible

- common/components/activity/activity-items-table.ts
[ch27422] When adding a new activity input level item, the focus should be on the item that was just added , not the first item in the list
> [ch27422] When adding a new activity input level item, the focus should be on the item that was just added , not the first item in the list

- intervention-workplan/results-structure/results-structure.ts
[ch26909] Add tooltip on "Add CP Output" plus button on the results card. The tooltip should say "Add CP Output" similar to supply upload
> [ch26909] "Add CP Output" tooltip color change

- intervention-workplan/budget-summary/budget-summary.ts
[ch28107] Budget Currency tooltip missing when the currency of the PD and the FR currency are not the same
> [ch28107] Budget Currency tooltip missing when the currency of the PD and the FR currency are not the same

- intervention-workplan/budget-summary/budget-summary.ts
[ch28167] Fund reservation related tooltip showing up again when there is no Fund reservation (regression issue)
> [ch28167] Fund reservation related tooltip showing up again when there is no Fund reservation (regression issue)

- intervention-workplan/budget-summary/budget-summary.ts
[ch28169] Fund reservation related tooltips should not be displayed for the Partner user
> [ch28169] Fund reservation related tooltips should not be displayed for the Partner user

- intervention-timing/intervention-dates/intervention-dates.ts
[ch28187] Timing tab: FR End date warning tooltip not cleared when the FR End Date is corrected
> [ch28187] Timing tab: FR End date warning tooltip not cleared when the FR End Date is corrected

- intervention-workplan/results-structure/cp-output-level.ts
[ch29467] Results Structure - hover style present for CP Programme Output when section is readonly
> [ch29467] Results Structure - hover style present for CP Programme Output when section is readonly

- intervention-workplan/results-structure/results-structure.ts
[ch29563] [Results Structure-Standard view]: Cancel hover functionality when in comment mode on PD Output description
> [ch29563] [Results Structure-Standard view]: Cancel hover functionality when in comment mode on PD Output description

- common/components/comments/comment.styles.ts
[ch29557] Comment mode: Time stamp too close to name
> [ch29557] Comment mode: Time stamp too close to name

- intervention-workplan-editor/time-intervals/time-intervals.ts
[ch29606] On results structure in read view for activity time periods, the hand pointer appears giving the user the impression that it’s clickable
> [ch29606] On results structure in read view for activity time periods, the hand pointer appears giving the user the impression that it’s clickable

- intervention-strategy/geographical-coverage/geographical-coverage.ts
[ch29592] Geographical Coverage: Location drop-down jumps to right/left while selecting/deselecting locations from the list
> [ch29592] Geographical Coverage: Location drop-down jumps to right/left while selecting/deselecting locations from the list

- intervention-tabs.ts
[ch29703] Progress tab: display all options when a UNICEF Super user accesses  ePD
> [ch29703] Don't show Progress tab in ePD

- intervention-workplan/results-structure/pd-activities.ts
- intervention-workplan/results-structure/pd-indicators.ts
[ch31350] Results Structure: Remove redundant 'Indicator'/'Activity Name' labels in standard view, Development status
> [ch31350] Results Structure: Remove redundant 'Indicator'/'Activity Name' labels in standard view, Development status

- intervention-workplan/results-structure/pd-activities.ts
- intervention-workplan/results-structure/pd-indicators.ts
[ch31359] Results Structure: Column header not displayed in other PD statuses (except Development)
> [ch31359] Results Structure: Column header not displayed in other PD statuses (except Development)

- common/components/comments/comments-mixin.ts
[ch32275] Editor: Comment mode borders not disabled when the toggle is off
> [ch32275] Editor: Comment mode borders not disabled when the toggle is off

- intervention-workplan/results-structure/modals/indicator-dialog/mixins/save-indicator-mixin.ts
[ch30057] Add a toast when a validation error is not visible
> [ch30057] Add a toast when a validation error is not visible

- common/components/intervention/start-review.ts
[ch32592] Make the field `Review type` required in Send for Review dialog
> [ch32592] Make the field `Review type` required in Send for Review dialog

- common/layout/page-content-header/intervention-page-content-header.ts
[ch31952] The Search section of the dropdown is covered by the header
> [ch31952] The Search section of the dropdown is covered by the header

- intervention-tabs.ts
[ch32703] When you refresh in an active comment mode, the toggle looks active, but you are no longer in comment mode
> [ch32703] When you refresh in an active comment mode, the toggle looks active, but you are no longer in comment mode

- common/components/intervention/review-checklist-popup.ts
[ch32810] Review date when selecting today via the datepicker the field doesn't get updated with a value and remains None
> [ch32810] Review date when selecting today via the datepicker the field doesn't get updated with a value and remains None

- intervention-actions/intervention-actions.styles.ts
[ch33136] In Arabic, the arrow on the Send back action should point in the other direction
> [ch33136] In Arabic, the arrow on the Send back action should point in the other direction
